/// Link-creation grant issuance — the keyserver half of the view-once
/// link lane.
///
/// ## The one thing to understand about this file
///
/// A grant proves **"a vouched OSL client asked for this"** and nothing
/// else. It is anonymous by construction: the payload is exactly
/// `aud` / `exp` / `jti`, and there is no code path here that can add a
/// user id, a licence tier, a device id or a counter to it.
///
/// That is not an oversight to be tidied up later, it is the design:
///
/// - The cipher-store is the party that gets subpoenaed, because it is
///   the party that holds bytes. It must be structurally unable to
///   answer "who made this link", the same way it is structurally unable
///   to answer "what does this ciphertext say". Anything identifying in
///   the grant would put that answer inside a request the store
///   receives, and a store that *could* answer will eventually be asked.
/// - The identity split is deliberate: the keyserver knows who asked and
///   never sees the link; the cipher-store sees the link and never knows
///   who asked. Neither side alone can correlate a person to a link, and
///   correlating them requires compromising both.
/// - Enforcement does not need identity in the grant. Revoking a bad
///   actor happens *here*, where identities already live, by refusing to
///   issue. Putting the id in the token buys nothing and costs the
///   property above.
///
/// `cipher-store-cf/test/link-grant.test.ts` pins the claim set
/// byte-for-byte, so adding a field breaks that test on purpose. If you
/// are here because you want per-user attribution at the store: the
/// answer is no, and the test says so before the review does.
///
/// ## Wire format (mirrors `cipher-store-cf/src/lib/link-grant.ts`)
///
///   Authorization: OSL-Link-Grant <base64url(payload)>.<base64url(sig)>
///   payload = {"aud":"osl-link-create","exp":<unix>,"jti":"<32 hex>"}
///   sig     = Ed25519( "OSL-LINK-GRANT-v1" || 0x00 || payloadBytes )
///
/// The payload is emitted by a single `format`-style template with fixed
/// field order so the issuer, the verifier and
/// `crypto::view_once_link::grant_payload_json` agree byte-for-byte.
///
/// ## Key custody
///
/// The issuer keypair is generated by the operator (see
/// `scripts/gen-link-grant-key.mjs`) and exists in exactly two places:
///
///   - the private half as the `LINK_GRANT_SECRET_B64` Worker secret on
///     *this* Worker, never in the repo, never in a build artefact;
///   - the public half as `LINK_GRANT_PUBKEY_B64` on **both** Workers —
///     the cipher-store needs it to verify, this Worker keeps a copy
///     purely so a mismatched pair fails loudly at issuance instead of
///     silently 401-ing every link creation.
///
/// Both must be present or issuance is refused. An issuer that cannot
/// prove its own key pairs up is not a working issuer.

import type { Env } from "../env.js";

export const GRANT_SCHEME = "OSL-Link-Grant";
export const GRANT_AUDIENCE = "osl-link-create";
export const GRANT_DOMAIN = "OSL-LINK-GRANT-v1";

/// What the cipher-store will accept as a ceiling. Mirrors
/// `MAX_GRANT_LIFETIME_SECONDS` in `cipher-store-cf/src/lib/link-grant.ts`
/// and `crypto::view_once_link::MAX_GRANT_LIFETIME_SECONDS`.
export const MAX_GRANT_LIFETIME_SECONDS = 600;

/// What this issuer actually mints. Deliberately half the ceiling: a
/// grant is redeemed within one round-trip of being issued, so five
/// minutes is already generous, and staying under the cap means a clock
/// skew of a couple of minutes between the two Workers cannot turn every
/// grant into a `grant_lifetime` refusal.
export const GRANT_LIFETIME_SECONDS = 300;

/// PKCS#8 prefix for an Ed25519 private key carrying a raw 32-byte seed.
/// SEQUENCE { INTEGER 0, SEQUENCE { OID 1.3.101.112 }, OCTET STRING {
/// OCTET STRING (32) } } — fixed length, so the seed can be wrapped
/// without a DER encoder.
const PKCS8_ED25519_PREFIX = new Uint8Array([
  0x30, 0x2e, 0x02, 0x01, 0x00, 0x30, 0x05, 0x06, 0x03, 0x2b, 0x65, 0x70,
  0x04, 0x22, 0x04, 0x20,
]);

const SEED_BYTES = 32;
const PKCS8_BYTES = PKCS8_ED25519_PREFIX.byteLength + SEED_BYTES;
const PUBLIC_KEY_BYTES = 32;

/// Accepts standard or URL-safe base64, padded or not. Operators paste
/// these by hand; refusing a URL-safe paste would be a footgun with no
/// security value, since the decoded bytes are length-checked anyway.
function decodeBase64Loose(value: string): Uint8Array | null {
  const normalised = value.trim().replace(/-/g, "+").replace(/_/g, "/");
  const padded = normalised + "=".repeat((4 - (normalised.length % 4)) % 4);
  try {
    const binary = atob(padded);
    const out = new Uint8Array(binary.length);
    for (let i = 0; i < binary.length; i++) out[i] = binary.charCodeAt(i);
    return out;
  } catch {
    return null;
  }
}

function base64Url(bytes: Uint8Array): string {
  let binary = "";
  for (const b of bytes) binary += String.fromCharCode(b);
  return btoa(binary).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/g, "");
}

/// Wrap a raw 32-byte Ed25519 seed in the minimal PKCS#8 envelope
/// WebCrypto insists on for private-key import. WebCrypto has no "raw"
/// import for private keys, so an operator holding a seed would
/// otherwise be stuck.
export function pkcs8FromSeed(seed: Uint8Array): Uint8Array {
  const out = new Uint8Array(PKCS8_BYTES);
  out.set(PKCS8_ED25519_PREFIX, 0);
  out.set(seed, PKCS8_ED25519_PREFIX.byteLength);
  return out;
}

export interface IssuerKey {
  signingKey: CryptoKey;
  publicKey: Uint8Array;
}

/// Cached per isolate. Keyed on the configured strings so a test (or a
/// secret rotation that recycles the isolate) cannot be served a stale
/// key. Holds no plaintext and is never logged.
let cached: { secret: string; pub: string; key: IssuerKey } | null = null;

/// The exact bytes the boot self-test signs and verifies. Domain-tagged
/// so this can never collide with a real grant: it is not valid JSON and
/// would fail `aud` parsing even if it somehow reached a verifier.
const SELF_TEST_MESSAGE = new TextEncoder().encode(
  "OSL-LINK-GRANT-v1\x00issuer-self-test",
);

/// Load, validate and self-test the issuer keypair.
///
/// Returns `null` for every failure — unset, malformed, wrong length,
/// unusable runtime, or a private/public pair that does not actually
/// pair up. The caller turns `null` into a 503. There is no partial
/// success: an issuer that cannot prove it holds the key the
/// cipher-store trusts must not mint tokens that will be refused there.
export async function loadIssuerKey(env: Env): Promise<IssuerKey | null> {
  const secretB64 = env.LINK_GRANT_SECRET_B64;
  const pubB64 = env.LINK_GRANT_PUBKEY_B64;
  if (!secretB64 || !pubB64) return null;
  if (cached && cached.secret === secretB64 && cached.pub === pubB64) {
    return cached.key;
  }

  const secretBytes = decodeBase64Loose(secretB64);
  const publicKey = decodeBase64Loose(pubB64);
  if (!secretBytes || !publicKey) return null;
  if (publicKey.byteLength !== PUBLIC_KEY_BYTES) return null;

  let pkcs8: Uint8Array;
  if (secretBytes.byteLength === SEED_BYTES) {
    pkcs8 = pkcs8FromSeed(secretBytes);
  } else if (secretBytes.byteLength === PKCS8_BYTES) {
    pkcs8 = secretBytes;
  } else {
    return null;
  }

  try {
    const signingKey = await crypto.subtle.importKey(
      "pkcs8",
      pkcs8,
      { name: "Ed25519" },
      false,
      ["sign"],
    );
    const verifyKey = await crypto.subtle.importKey(
      "raw",
      publicKey,
      { name: "Ed25519" },
      false,
      ["verify"],
    );
    // Pair check. A mismatched secret/public pair is the operator error
    // this catches: without it every grant verifies fine here and is
    // refused at the cipher-store with `grant_signature`, which looks
    // like an attack rather than a typo.
    const probe = await crypto.subtle.sign(
      { name: "Ed25519" },
      signingKey,
      SELF_TEST_MESSAGE,
    );
    const paired = await crypto.subtle.verify(
      { name: "Ed25519" },
      verifyKey,
      probe,
      SELF_TEST_MESSAGE,
    );
    if (!paired) {
      console.error("[link-grant] issuer key pair does not match; refusing to issue");
      return null;
    }
    const key: IssuerKey = { signingKey, publicKey };
    cached = { secret: secretB64, pub: pubB64, key };
    return key;
  } catch {
    console.error("[link-grant] issuer key unusable; refusing to issue");
    return null;
  }
}

/// Test-only cache reset. Production never calls this; the cache key
/// already covers rotation.
export function resetIssuerKeyCache(): void {
  cached = null;
}

/// Fresh 16-byte `jti`, lowercase hex — the exact shape the verifier's
/// `/^[0-9a-f]{32}$/` accepts and the cipher-store burns on redemption.
export function newGrantJti(): string {
  const bytes = new Uint8Array(16);
  crypto.getRandomValues(bytes);
  let hex = "";
  for (const b of bytes) hex += b.toString(16).padStart(2, "0");
  return hex;
}

/// The canonical grant payload. Field order is fixed and the encoding is
/// a template rather than `JSON.stringify` over an object literal so
/// that the byte string cannot drift with a refactor.
///
/// THREE CLAIMS, NO MORE. See the header comment before adding a fourth.
export function grantPayloadJson(expUnixSeconds: number, jtiHex: string): Uint8Array {
  return new TextEncoder().encode(
    `{"aud":"${GRANT_AUDIENCE}","exp":${expUnixSeconds},"jti":"${jtiHex}"}`,
  );
}

/// Domain-separated signing input. The `0x00` cannot occur inside the
/// ASCII domain, so the boundary is unambiguous.
export function grantSigningBytes(payload: Uint8Array): Uint8Array {
  const domain = new TextEncoder().encode(GRANT_DOMAIN);
  const out = new Uint8Array(domain.byteLength + 1 + payload.byteLength);
  out.set(domain, 0);
  out[domain.byteLength] = 0x00;
  out.set(payload, domain.byteLength + 1);
  return out;
}

export interface MintedGrant {
  /// Ready to use verbatim as the `Authorization` header value.
  authorization: string;
  /// Unix seconds. The client uses it only to decide whether to bother
  /// sending; the cipher-store re-checks it against its own clock.
  expiresAt: number;
}

/// Mint one anonymous, single-use, short-lived grant.
///
/// `nowSeconds` is injectable so the lifetime invariant can be tested
/// without a fake clock. It is never taken from the request.
export async function mintGrant(
  key: IssuerKey,
  nowSeconds: number = Math.floor(Date.now() / 1000),
): Promise<MintedGrant> {
  const expiresAt = nowSeconds + GRANT_LIFETIME_SECONDS;
  const payload = grantPayloadJson(expiresAt, newGrantJti());
  const signature = new Uint8Array(
    await crypto.subtle.sign({ name: "Ed25519" }, key.signingKey, grantSigningBytes(payload)),
  );
  return {
    authorization: `${GRANT_SCHEME} ${base64Url(payload)}.${base64Url(signature)}`,
    expiresAt,
  };
}
