import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import test from "node:test";
import { createServer } from "vite";
import { launchChrome } from "../../../scripts/lib/cdp-harness.mjs";
import { readPng } from "./lib/png-pixels.mjs";

/**
 * TASK 0856 - the honest tile status page, photographed on Linux.
 *
 * The finish line is "a Linux screenshot shows an honest placing-only service
 * status page", so this capture has to prove four separate things about the
 * pixels rather than just take a picture:
 *
 *   1. PLACING-ONLY, and derived. The capability label is generated by
 *      tile-status-page.ts on the TASK 0804 ladder from the evidence the
 *      catalog carries. Telegram is the only connected app that reaches
 *      "Placing only", and it reaches it because it holds the only live carry
 *      receipt this project has ever earned. The second render (Discord, which
 *      has no receipt) is photographed too, and the two images are compared:
 *      if the label region does not change, nothing on screen is being drawn
 *      from the data.
 *   2. HONEST. Every future-promise phrase TASK 0853 bans is searched for in
 *      the rendered body text AND in the accessibility tree. The page may not
 *      promise anything.
 *   3. A STATUS PAGE, not a badge. The real capability, both plain limits, the
 *      useful action and Back to Home all have to be laid out inside the
 *      1280x800 window and drawn in more than one colour.
 *   4. From the catalog. The fixture renders loadNativeApps() - the same list
 *      services.test.ts holds against claim_state.rs - not a JSON prop typed
 *      into this file.
 */

const APP_ROOT = path.resolve(import.meta.dirname, "..");
const EVIDENCE_DIR = path.join(APP_ROOT, "screenshots", "evidence");
const PNG_PATH = path.join(EVIDENCE_DIR, "task-0856-tile-status-page-1280x800.png");
const OTHER_PNG_PATH = path.join(EVIDENCE_DIR, "task-0856-tile-status-page-discord-1280x800.png");
const TREE_PATH = path.join(EVIDENCE_DIR, "task-0856-tile-status-page-screen-tree.json");
const FIXTURE_PAGE = "screenshots/task-0856-tile-status-page-fixture.html";
const WINDOW = Object.freeze({ width: 1280, height: 800 });

/** This file's own copy of the ban list, so it is a check and not a mirror. */
const FUTURE_PROMISE_PHRASES = Object.freeze([
  "coming soon", "coming later", "coming", "soon", "shortly", "eventually", "later",
  "in future", "in a future release", "future release", "future version", "next release",
  "upcoming", "planned", "roadmap", "stay tuned", "on the way", "in the works", "under way",
  "work in progress", "will be", "will support", "will let", "we will", "we'll", "promise",
  "arriving", "launching", "not yet supported",
]);

/** A region that changes between two apps is a region drawing the data. */
const DRAWN_MIN_MEAN_ABS_DIFF = 4;

function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/gu, "\\$&");
}

function promisesIn(text) {
  return FUTURE_PROMISE_PHRASES.filter((phrase) => {
    const body = escapeRegExp(phrase).replace(/\\?\s+/gu, "\\s+");
    return new RegExp(`\\b${body}\\b`, "iu").test(text);
  });
}

async function startVite() {
  const server = await createServer({
    root: APP_ROOT,
    logLevel: "error",
    server: { host: "127.0.0.1", port: 0, strictPort: false },
  });
  await server.listen();
  const address = server.httpServer?.address();
  if (!address || typeof address === "string") throw new Error("Vite did not expose a TCP address");
  return { server, url: `http://127.0.0.1:${address.port}/` };
}

function accessibilityTreeText(nodes) {
  return nodes
    .flatMap((node) => [node.role?.value, node.name?.value, node.value?.value, node.description?.value])
    .filter((value) => typeof value === "string" && value.trim())
    .join("\n");
}

async function evaluateValue(page, expression) {
  const evaluated = await page.send("Runtime.evaluate", {
    expression,
    returnByValue: true,
    awaitPromise: true,
  });
  if (evaluated.exceptionDetails) {
    throw new Error(
      evaluated.exceptionDetails.exception?.description
        || evaluated.exceptionDetails.text
        || "page evaluation threw",
    );
  }
  return evaluated.result.value;
}

function uniqueColoursInRegion(image, rect) {
  const seen = new Set();
  for (let y = Math.floor(rect.y); y < Math.ceil(rect.y + rect.height); y += 1) {
    for (let x = Math.floor(rect.x); x < Math.ceil(rect.x + rect.width); x += 1) {
      const offset = (y * image.width + x) * 4;
      seen.add(`${image.pixels[offset]},${image.pixels[offset + 1]},${image.pixels[offset + 2]}`);
    }
  }
  return seen.size;
}

function rectMeanAbsDiff(left, right, rect) {
  const x0 = Math.round(rect.x);
  const y0 = Math.round(rect.y);
  const width = Math.round(rect.width);
  const height = Math.round(rect.height);
  assert.ok(width > 0 && height > 0, "compared rectangle is empty");
  let total = 0;
  let samples = 0;
  for (let y = y0; y < y0 + height; y += 1) {
    for (let x = x0; x < x0 + width; x += 1) {
      if (x < 0 || y < 0 || x >= left.width || y >= left.height) {
        throw new Error(`compared rectangle falls outside the screenshot at ${x},${y}`);
      }
      const offset = (y * left.width + x) * 4;
      total += Math.abs(left.pixels[offset] - right.pixels[offset]);
      total += Math.abs(left.pixels[offset + 1] - right.pixels[offset + 1]);
      total += Math.abs(left.pixels[offset + 2] - right.pixels[offset + 2]);
      samples += 3;
    }
  }
  return total / samples;
}

const RENDER = (tileId) => `new Promise((resolve, reject) => {
  const deadline = Date.now() + 20000;
  const tick = () => {
    if (typeof window.task0856Render === "function") {
      window.task0856Render(${JSON.stringify(tileId)});
      requestAnimationFrame(() => requestAnimationFrame(resolve));
      return;
    }
    if (Date.now() > deadline) {
      reject(new Error("the tile status page did not render"));
      return;
    }
    setTimeout(tick, 25);
  };
  tick();
})`;

const READ_SCREEN = `(() => {
  const rect = (element) => {
    const box = element?.getBoundingClientRect();
    return box ? { x: box.x, y: box.y, width: box.width, height: box.height } : null;
  };
  const page = document.querySelector("[data-tile-status-page]");
  const capability = document.querySelector("[data-tile-status-capability]");
  const claim = document.querySelector("[data-tile-status-claim]");
  const next = document.querySelector(".tile-status-next");
  const back = document.querySelector(".tile-status-back");
  const rows = (selector) => [...document.querySelectorAll(selector)].map((node) => ({
    id: node.dataset.tileStatusCan || node.dataset.tileStatusLimit || "",
    text: node.textContent.replace(/\\s+/gu, " ").trim(),
  }));
  return {
    title: document.title,
    heading: document.querySelector("#tile-status-title")?.textContent?.trim() || "",
    text: document.body.innerText.replace(/\\s+/gu, " ").trim(),
    tileId: page?.dataset.tileStatusPage || "",
    route: page?.dataset.tileStatusRoute || "",
    capabilityLabel: capability?.textContent?.trim() || "",
    capabilityLabelElements: document.querySelectorAll("[data-tile-status-capability]").length,
    claimLabel: claim?.textContent?.trim() || "",
    capabilitySentence: document.querySelector("[data-tile-status-capability-sentence]")?.textContent?.trim() || "",
    explanation: document.querySelector("[data-tile-status-explanation]")?.textContent?.trim() || "",
    can: rows("[data-tile-status-can]"),
    limits: rows("[data-tile-status-limit]"),
    limitCount: Number(document.querySelector("[data-tile-status-limit-count]")?.dataset.tileStatusLimitCount || "-1"),
    nextLabel: next?.textContent?.trim() || "",
    nextId: next?.id || "",
    nextHandler: next?.dataset.tileStatusHandler || "",
    nextTarget: next?.dataset.tileStatusAction || "",
    backLabel: back?.textContent?.trim() || "",
    backId: back?.id || "",
    backTarget: back?.dataset.tileStatusAction || "",
    mains: document.querySelectorAll("main").length,
    routeHeadings: document.querySelectorAll("#route-heading").length,
    rects: {
      heading: rect(document.querySelector("#tile-status-title")),
      capabilityLabel: rect(capability),
      capabilitySentence: rect(document.querySelector("[data-tile-status-capability-sentence]")),
      explanation: rect(document.querySelector("[data-tile-status-explanation]")),
      limits: rect(document.querySelector("[data-tile-status-limit-count]")),
      actions: rect(document.querySelector(".tile-status-actions")),
      next: rect(next),
      back: rect(back),
    },
  };
})()`;

function assertInsideWindow(screen, label) {
  for (const [name, rect] of Object.entries(screen.rects)) {
    assert.ok(rect, `${label}: ${name} was not laid out`);
    assert.ok(rect.width > 0 && rect.height > 0, `${label}: ${name} has no area`);
    assert.ok(rect.x >= 0 && rect.y >= 0, `${label}: ${name} starts outside the window`);
    assert.ok(rect.x + rect.width <= WINDOW.width, `${label}: ${name} runs past the window width`);
    assert.ok(rect.y + rect.height <= WINDOW.height, `${label}: ${name} runs past the window height`);
  }
}

test("TASK 0856 photographs an honest placing-only service status page on Linux", async () => {
  mkdirSync(EVIDENCE_DIR, { recursive: true });
  const { server, url } = await startVite();
  const chrome = await launchChrome({
    args: [
      "--headless=new",
      "--remote-debugging-port=0",
      "--no-sandbox",
      "--disable-gpu",
      "--force-device-scale-factor=1",
      `--window-size=${WINDOW.width},${WINDOW.height}`,
      "about:blank",
    ],
  });
  const page = await chrome.openPage();
  try {
    await page.send("Emulation.setDeviceMetricsOverride", {
      width: WINDOW.width,
      height: WINDOW.height,
      deviceScaleFactor: 1,
      mobile: false,
      screenWidth: WINDOW.width,
      screenHeight: WINDOW.height,
    });
    await page.navigate(`${url}${FIXTURE_PAGE}`, { timeoutMs: 30_000 });
    await page.send("Accessibility.enable");

    // The whole catalog, straight out of the page, so the "only one app is
    // placing-only" claim is measured here and not taken from the unit test.
    const catalog = await evaluateValue(page, `new Promise((resolve, reject) => {
      const deadline = Date.now() + 20000;
      const tick = () => {
        if (typeof window.task0856Catalog === "function") { resolve(window.task0856Catalog()); return; }
        if (Date.now() > deadline) { reject(new Error("the fixture never loaded the catalog")); return; }
        setTimeout(tick, 25);
      };
      tick();
    })`);
    const placingOnly = catalog.filter((entry) => entry.page.capabilityLabel === "Placing only").map((entry) => entry.id);
    console.log(`TASK0856_CATALOG_SIZE=${catalog.length}`);
    for (const entry of catalog) {
      console.log(`TASK0856_CAPABILITY ${entry.id}=${entry.page.capabilityLabel} can=${entry.page.can.length} limits=${entry.page.limits.length}`);
    }
    console.log(`TASK0856_PLACING_ONLY=${placingOnly.join(",") || "none"}`);
    assert.deepEqual(placingOnly, ["telegram"], "exactly one connected app should be placing-only");

    await evaluateValue(page, RENDER("telegram"));
    const screen = await evaluateValue(page, READ_SCREEN);
    const ax = await page.send("Accessibility.getFullAXTree");
    const axText = accessibilityTreeText(ax.nodes ?? []);
    const pageText = [screen.text, axText].join("\n");

    // 1. the real capability, generated.
    assert.equal(screen.tileId, "telegram");
    assert.equal(screen.route, "service:telegram");
    assert.equal(screen.capabilityLabel, "Placing only");
    assert.equal(screen.capabilityLabelElements, 1);
    assert.equal(screen.claimLabel, "Not claimed");
    assert.equal(screen.heading, "Telegram");
    assert.equal(screen.title, "Telegram");
    assert.equal(screen.capabilitySentence, "live carry capability is proven; delivery is not live-proven");
    assert.ok(screen.explanation.includes("live carry receipt"), `explanation is not the generated one: ${screen.explanation}`);

    // 2. the plain limits: one line per capability OSL does not have here.
    assert.equal(screen.limitCount, 2);
    assert.deepEqual(screen.limits.map((row) => row.id), ["reading", "protectedMessaging"]);
    assert.deepEqual(screen.can.map((row) => row.id), ["placing", "opening"]);
    for (const row of [...screen.can, ...screen.limits]) {
      assert.ok(row.text.length > 30, `${row.id} is a stub: ${row.text}`);
    }

    // 3. the useful action, and 4. Back to Home.
    assert.equal(screen.nextLabel, "Open Telegram in a separate OSL profile");
    assert.equal(screen.nextId, "embedded-service-setup");
    assert.equal(screen.nextHandler, "data-home-app");
    assert.equal(screen.backLabel, "Back to Home");
    assert.equal(screen.backId, "native-app-back");
    assert.equal(screen.backTarget, "home");

    // One page, one landmark.
    assert.equal(screen.mains, 1);
    assert.equal(screen.routeHeadings, 1);
    assertInsideWindow(screen, "telegram");

    // Honest: no future promise, anywhere a person or a screen reader can see.
    const bodyPromises = promisesIn(screen.text);
    const axPromises = promisesIn(axText);
    console.log(`TASK0856_BODY_FUTURE_PROMISES=${bodyPromises.length}${bodyPromises.length ? ` (${bodyPromises.join("|")})` : ""}`);
    console.log(`TASK0856_AX_FUTURE_PROMISES=${axPromises.length}${axPromises.length ? ` (${axPromises.join("|")})` : ""}`);
    assert.deepEqual(bodyPromises, [], "the page body promises a future");
    assert.deepEqual(axPromises, [], "the accessibility tree promises a future");

    const REQUIRED_TEXT = Object.freeze([
      "Telegram",
      "Placing only",
      "Not claimed",
      "live carry capability is proven; delivery is not live-proven",
      "What OSL can do here",
      "What OSL cannot do here",
      "OSL cannot read a protected message back out of Telegram",
      "OSL has never carried a protected message between two people through Telegram",
      "Open Telegram in a separate OSL profile",
      "Back to Home",
    ]);
    // Case-folded: the two chips are painted `text-transform: uppercase`, so
    // innerText reports them as drawn ("PLACING ONLY") rather than as authored.
    const foldedText = pageText.toLowerCase();
    for (const required of REQUIRED_TEXT) {
      assert.match(foldedText, new RegExp(escapeRegExp(required.toLowerCase()), "u"), `missing screen text: ${required}`);
    }

    const png = await page.screenshot({ fromSurface: true });
    writeFileSync(PNG_PATH, png);
    const shot = readPng(png);
    assert.equal(shot.width, WINDOW.width);
    assert.equal(shot.height, WINDOW.height);

    // The control render: the same page for an app with no carry receipt.
    await evaluateValue(page, RENDER("discord"));
    const other = await evaluateValue(page, READ_SCREEN);
    const otherPng = await page.screenshot({ fromSurface: true });
    writeFileSync(OTHER_PNG_PATH, otherPng);
    const otherShot = readPng(otherPng);
    assert.equal(other.capabilityLabel, "Opens the app");
    assert.equal(other.limitCount, 3 + 2, "Discord's limits should include its two open conditions");
    for (const [name, rect] of Object.entries(other.rects)) {
      assert.ok(rect && rect.width > 0 && rect.height > 0, `discord: ${name} was not laid out`);
    }
    // Discord carries five limits and two open conditions, so its page is
    // taller than the window and its action row sits below the fold in a
    // scrolling `.content-viewport`. That is reported, not asserted away: the
    // page the finish line photographs is the placing-only one, and that one
    // fits whole (checked above).
    const controlBelowFold = other.rects.actions.y + other.rects.actions.height - WINDOW.height;
    console.log(`TASK0856_CONTROL_ACTIONS_BELOW_FOLD_PX=${Math.max(0, Math.round(controlBelowFold))}`);

    // Only regions that did NOT move between the two renders are compared: a
    // rectangle that shifted would make a pixel difference prove relayout
    // rather than data. The header is above every variable-height block, so it
    // is the honest place to measure.
    const comparedRects = {};
    for (const key of ["heading", "capabilityLabel", "capabilitySentence"]) {
      const mine = screen.rects[key];
      const theirs = other.rects[key];
      // Same origin, so the compared pixels are the same place on both pages.
      // The widths differ because these boxes shrink to their text ("Telegram"
      // is wider than "Discord", "PLACING ONLY" than "OPENS THE APP"), so the
      // overlap is what gets compared.
      assert.equal(mine.x, theirs.x, `${key} moved horizontally between the two apps`);
      assert.equal(mine.y, theirs.y, `${key} moved vertically between the two apps`);
      comparedRects[key] = {
        x: mine.x,
        y: mine.y,
        width: Math.min(mine.width, theirs.width),
        height: Math.min(mine.height, theirs.height),
      };
    }
    const diffs = Object.fromEntries(
      Object.entries(comparedRects).map(([key, rect]) => [key, rectMeanAbsDiff(shot, otherShot, rect)]),
    );
    const colours = {
      capabilityLabel: uniqueColoursInRegion(shot, screen.rects.capabilityLabel),
      capabilitySentence: uniqueColoursInRegion(shot, screen.rects.capabilitySentence),
      limits: uniqueColoursInRegion(shot, screen.rects.limits),
      actions: uniqueColoursInRegion(shot, screen.rects.actions),
    };
    const sha256 = createHash("sha256").update(png).digest("hex");
    const otherSha256 = createHash("sha256").update(otherPng).digest("hex");

    writeFileSync(TREE_PATH, JSON.stringify({
      task: "0856",
      url: `${url}${FIXTURE_PAGE}`,
      window: WINDOW,
      platform: process.platform,
      required: REQUIRED_TEXT,
      catalog,
      placingOnly,
      png: { path: PNG_PATH, bytes: png.length, sha256 },
      controlPng: { path: OTHER_PNG_PATH, bytes: otherPng.length, sha256: otherSha256 },
      placingOnlyScreen: screen,
      controlScreen: other,
      comparedRects,
      diffs,
      colours,
      futurePromises: { body: bodyPromises, accessibility: axPromises },
      axNodes: ax.nodes,
    }, null, 2));

    assert.notEqual(sha256, otherSha256, "both captures are the same image");
    for (const [name, value] of Object.entries(diffs)) {
      assert.ok(value >= DRAWN_MIN_MEAN_ABS_DIFF, `${name} looks the same for both apps, so it is not drawn from the data (${value})`);
    }
    for (const [name, value] of Object.entries(colours)) {
      assert.ok(value > 8, `${name} looks blank: ${value} colours`);
    }
    assert.ok(png.length > 10_000, `PNG too small: ${png.length}`);
    assert.equal(process.platform, "linux", "this capture is the Linux one");

    console.log(`TASK0856_PLATFORM=${process.platform}`);
    console.log(`TASK0856_PNG=${PNG_PATH}`);
    console.log(`TASK0856_CONTROL_PNG=${OTHER_PNG_PATH}`);
    console.log(`TASK0856_TREE=${TREE_PATH}`);
    console.log(`TASK0856_WINDOW=${shot.width}x${shot.height}`);
    console.log(`TASK0856_PNG_BYTES=${png.length}`);
    console.log(`TASK0856_PNG_SHA256=${sha256}`);
    console.log(`TASK0856_CONTROL_PNG_BYTES=${otherPng.length}`);
    console.log(`TASK0856_CONTROL_PNG_SHA256=${otherSha256}`);
    console.log(`TASK0856_TILE=${screen.tileId} ROUTE=${screen.route}`);
    console.log(`TASK0856_CAPABILITY_LABEL=${screen.capabilityLabel}`);
    console.log(`TASK0856_CLAIM_LABEL=${screen.claimLabel}`);
    console.log(`TASK0856_CAPABILITY_SENTENCE=${screen.capabilitySentence}`);
    for (const row of screen.can) console.log(`TASK0856_CAN ${row.id}=${row.text}`);
    for (const row of screen.limits) console.log(`TASK0856_LIMIT ${row.id}=${row.text}`);
    console.log(`TASK0856_LIMIT_COUNT=${screen.limitCount}`);
    console.log(`TASK0856_NEXT_ACTION=${screen.nextLabel} | id=${screen.nextId} | handler=${screen.nextHandler} | target=${screen.nextTarget}`);
    console.log(`TASK0856_BACK=${screen.backLabel} | id=${screen.backId} | target=${screen.backTarget}`);
    console.log(`TASK0856_CONTROL_CAPABILITY_LABEL=${other.capabilityLabel} (discord)`);
    for (const [name, value] of Object.entries(diffs)) console.log(`TASK0856_DIFF_${name.toUpperCase()}=${value.toFixed(4)}`);
    console.log(`TASK0856_COLOURS=${Object.entries(colours).map(([name, value]) => `${name}:${value}`).join("|")}`);
    console.log(`TASK0856_MAINS=${screen.mains} ROUTE_HEADINGS=${screen.routeHeadings}`);
  } finally {
    await page.close();
    await chrome.close();
    await server.close();
  }
}, { timeout: 180_000 });
