import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import test from 'node:test';
import { fileURLToPath } from 'node:url';
import { launchChrome } from '../../../scripts/lib/cdp-harness.mjs';
const dir=path.dirname(fileURLToPath(import.meta.url)), appRoot=path.resolve(dir,'..'), root=path.resolve(appRoot,'..','..'), evidence=path.join(root,'evidence','task-0378'), pngPath=path.join(evidence,'scrub-setup.png'), viewport={width:720,height:820};
async function port(){const s=createServer();await new Promise((r,j)=>{s.once('error',j);s.listen(0,'127.0.0.1',r)});const p=s.address().port;await new Promise(r=>s.close(r));return p}
test('TASK 0378 captures fixed Scrub and AutoScrub setup screen',async(t)=>{const p=await port(), child=(await import('node:child_process')).spawn(path.join(appRoot,'node_modules/.bin/vite'),['--host','127.0.0.1','--port',String(p),'--strictPort'],{cwd:appRoot,stdio:'ignore'});t.after(()=>child.kill('SIGTERM'));const url=`http://127.0.0.1:${p}/screenshots/task-0378-scrub-setup-fixture.html`;for(let i=0;i<300;i++){try{if((await fetch(url)).ok)break}catch{}await new Promise(r=>setTimeout(r,100))}const chrome=await launchChrome();t.after(()=>chrome.close());const page=await chrome.openPage();t.after(()=>page.close());await page.send('Emulation.setDeviceMetricsOverride',{...viewport,deviceScaleFactor:1,mobile:false});await page.navigate(url);const facts=await page.evaluate('globalThis.__TASK0378_FACTS');assert.equal(facts.title,'Scrub and AutoScrub setup');assert.equal(facts.controls.length,8);const tree=await page.send('Accessibility.getFullAXTree');const names=tree.nodes.map(n=>typeof n.name?.value==='string'?n.name.value.trim():'').filter(Boolean);const text=await page.evaluate('document.body.innerText');for(const name of facts.controls){assert.ok(names.includes(name),`AX missing ${name}`);assert.ok(text.includes(name),`image text source missing ${name}`)}mkdirSync(evidence,{recursive:true});writeFileSync(pngPath,await page.screenshot());const factsOut=(await import('node:child_process')).spawnSync('python3',[path.join(root,'scripts/vmqa/png-facts.py'),pngPath],{encoding:'utf8'});assert.equal(factsOut.status,0);const png=JSON.parse(factsOut.stdout);assert.equal(png.width,720);assert.equal(png.height,820);assert.ok(png.distinctColors>24);console.log(`TASK0378_SCREENSHOT_PATH=${path.relative(root,pngPath)}`);console.log(`TASK0378_WINDOW=720x820`);console.log(`TASK0378_TITLE=${facts.title}`);console.log(`TASK0378_CONTROLS=${facts.controls.join('|')}`);console.log(`TASK0378_AX_NAMES=${facts.controls.map(n=>`${n}:true`).join(',')}`);console.log(`TASK0378_PNG_FACTS width=${png.width} height=${png.height} distinctColors=${png.distinctColors}`)},90000);
