import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { createServer } from 'node:http';
import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import test from 'node:test';
import { fileURLToPath } from 'node:url';
import { setTimeout as delay } from 'node:timers/promises';
import { launchChrome } from '../../../scripts/lib/cdp-harness.mjs';
const dir=path.dirname(fileURLToPath(import.meta.url)), root=path.resolve(dir,'..'), repo=path.resolve(root,'..','..');
const out=path.join(repo,'evidence','task-0377'), pngPath=path.join(out,'choose-apps.png'), treePath=path.join(out,'choose-apps-screen-tree.json'), viewport={width:720,height:820};
const required=['Choose apps','Signal','WhatsApp','liam@example.test','+1 555 0100','Browser','Install','Open','Skip','Finish','Back'];
const quote=(value)=>value.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
async function port(){const s=createServer();await new Promise(r=>s.listen(0,'127.0.0.1',r));const p=s.address().port;await new Promise(r=>s.close(r));return p}
test('TASK 0377 captures Choose apps with detected accounts and choices',async(t)=>{const p=await port(),bin=path.join(root,'node_modules','.bin','vite'),child=spawn(bin,['--host','127.0.0.1','--port',String(p),'--strictPort'],{cwd:root,stdio:'ignore'});t.after(()=>{if(child.exitCode===null)child.kill('SIGTERM')});const url=`http://127.0.0.1:${p}/screenshots/task-0377-choose-apps-fixture.html`;for(let i=0;i<300;i++){try{if((await fetch(url)).ok)break}catch{}await delay(100)}const chrome=await launchChrome();t.after(()=>chrome.close());const page=await chrome.openPage();t.after(()=>page.close());await page.send('Emulation.setDeviceMetricsOverride',{...viewport,deviceScaleFactor:1,mobile:false});await page.navigate(url);const facts=await page.evaluate('globalThis.__TASK0377_FACTS');assert.equal(facts.title,'Choose apps');assert.deepEqual(facts.apps,['Signal','WhatsApp']);assert.deepEqual(facts.accounts,['Account: liam@example.test','Account: +1 555 0100']);const ax=await page.send('Accessibility.getFullAXTree');const names=ax.nodes.map(n=>typeof n.name?.value==='string'?n.name.value:'');const body=await page.evaluate('document.body.innerText');for(const x of required){assert.ok(names.some(n=>n.includes(x)),`AX contains ${x}`);assert.match(body,new RegExp(quote(x)))}mkdirSync(out,{recursive:true});const buf=await page.screenshot({clip:{x:0,y:0,width:viewport.width,height:viewport.height,scale:1}});writeFileSync(pngPath,buf);writeFileSync(treePath,JSON.stringify({url,viewport,required,facts,axTree:ax},null,2));assert.equal(buf.readUInt32BE(16),720);assert.equal(buf.readUInt32BE(20),820);assert.ok(buf.length>10000);assert.ok(new Set(buf).size>64);console.log(`TASK0377_TITLE=${facts.title}`);console.log(`TASK0377_APPS=${facts.apps.join('|')}`);console.log(`TASK0377_ACCOUNTS=${facts.accounts.join('|')}`);console.log(`TASK0377_CONTROLS=${required.slice(6).join('|')}`);console.log(`TASK0377_AX=${required.map(x=>`${x}:${names.some(n=>n.includes(x))}`).join(',')}`);console.log(`TASK0377_PNG=${pngPath}`);console.log(`TASK0377_TREE=${treePath}`);console.log(`TASK0377_PNG_BYTES=${buf.length}`);});
