import assert from "node:assert/strict";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import test from "node:test";
import { createServer } from "vite";
import { launchChrome } from "../../../scripts/lib/cdp-harness.mjs";

const APP_ROOT=path.resolve(import.meta.dirname,"..");
const ARTIFACT_DIR=path.join(APP_ROOT,"screenshots","artifacts");
const PNG_PATH=path.join(ARTIFACT_DIR,"task-0361-finish-saving-recovery-kit.png");
const TREE_PATH=path.join(ARTIFACT_DIR,"task-0361-finish-saving-recovery-kit-screen-tree.json");
const WINDOW=Object.freeze({width:1280,height:800});
const REQUIRED=["Finish saving your recovery kit","Your password","Show password","Show my recovery kit"];
const quoted=(value)=>value.replace(/[.*+?^${}()|[\]\\]/gu,"\\$&");
async function start(){const server=await createServer({root:APP_ROOT,logLevel:"error",server:{host:"127.0.0.1",port:0,strictPort:false}});await server.listen();const a=server.httpServer.address();return {server,url:`http://127.0.0.1:${a.port}/`};}
function text(nodes){return nodes.flatMap(n=>[n.role?.value,n.name?.value,n.value?.value,n.description?.value]).filter(v=>typeof v==="string"&&v.trim()).join("\n");}
test("TASK 0361 captures the fixed Finish saving recovery kit screen",async()=>{mkdirSync(ARTIFACT_DIR,{recursive:true});const {server,url}=await start();const chrome=await launchChrome({args:["--headless=new","--remote-debugging-port=0","--no-sandbox","--disable-gpu","--force-device-scale-factor=1",`--window-size=${WINDOW.width},${WINDOW.height}`,"about:blank"]});const page=await chrome.openPage();try{await page.send("Emulation.setDeviceMetricsOverride",{...WINDOW,deviceScaleFactor:1,mobile:false,screenWidth:WINDOW.width,screenHeight:WINDOW.height});await page.navigate(`${url}screenshots/task-0361-finish-saving-recovery-kit-fixture.html`,{timeoutMs:30000});await page.send("Accessibility.enable");await new Promise(r=>setTimeout(r,300));const screen=await page.evaluate(`(()=>({title:document.querySelector("#route-heading")?.textContent||"",text:document.body.innerText,controls:[...document.querySelectorAll("button,input")].map(e=>({tag:e.tagName.toLowerCase(),type:e.type||"",text:e.innerText||"",ariaLabel:e.getAttribute("aria-label")||"",label:e.id?(document.querySelector('label[for="'+CSS.escape(e.id)+'"]')?.innerText||""):""}))}))()`);const ax=await page.send("Accessibility.getFullAXTree");const combined=[screen.title,screen.text,JSON.stringify(screen.controls),text(ax.nodes||[])].join("\n").toLowerCase();for(const item of REQUIRED)assert.match(combined,new RegExp(quoted(item.toLowerCase())));const png=await page.screenshot({fromSurface:true});writeFileSync(PNG_PATH,png);writeFileSync(TREE_PATH,JSON.stringify({url:`${url}screenshots/task-0361-finish-saving-recovery-kit-fixture.html`,window:WINDOW,required:REQUIRED,screen,axNodes:ax.nodes},null,2));assert.equal(png.subarray(0,8).toString("hex"),"89504e470d0a1a0a");const dimensions={width:png.readUInt32BE(16),height:png.readUInt32BE(20)};assert.deepEqual(dimensions,WINDOW);assert.ok(png.length>10000);const unique=new Set(png).size;assert.ok(unique>64);console.log(`TASK0361_TITLE=${screen.title}`);console.log(`TASK0361_CONTROLS=${screen.controls.map(c=>c.label||c.ariaLabel||c.text).filter(Boolean).join("|")}`);console.log(`TASK0361_WINDOW=${dimensions.width}x${dimensions.height}`);console.log(`TASK0361_PNG=${PNG_PATH}`);console.log(`TASK0361_TREE=${TREE_PATH}`);console.log(`TASK0361_PNG_BYTES=${png.length}`);console.log(`TASK0361_PNG_UNIQUE_BYTES=${unique}`);}finally{await page.close();await chrome.close();await server.close();}}, {timeout:60000});
