import { describe, expect, it } from "vitest";
import { backlinksFor, filteredNotes, knowledgeGraphMarkup, markdownPreview, normalizeTags, noteTasks, notesWorkspaceMarkup, parseOslNote, parseOslNoteRevision, propertiesDashboardMarkup, taskDashboardMarkup, toggleTaskMarkdownLine, wikiLinks, type OslNote, type OslNoteRevision } from "./osl-notes";
const note = (id: string, title: string, body = ""): OslNote => ({ id, kind: "note", title, body, folder: "Work", tags: ["idea"], favorite: false, pinned: false, createdAt: 1, updatedAt: 2, deletedAt: null });
describe("OSL Notes", () => {
  it("strictly parses native records", () => { const value = note("a".repeat(32), "Hello"); expect(parseOslNote(value)).toEqual(value); expect(parseOslNote({ ...value, kind: "photo" })?.kind).toBe("photo"); expect(parseOslNote({ ...value, secret: true })).toBeNull(); });
  it("normalizes unique bounded tags", () => expect(normalizeTags(" Idea, idea, long   tag, ")).toEqual(["Idea", "long tag"]));
  it("searches content and respects trash", () => { const live = note("a".repeat(32), "Alpha", "needle"); const dead = { ...note("b".repeat(32), "Dead", "needle"), deletedAt: 3 }; expect(filteredNotes([live, dead], "needle", "all")).toEqual([live]); expect(filteredNotes([live, dead], "", "trash")).toEqual([dead]); });
  it("keeps encrypted pinned files first and renders nested folders in the command surface", () => { const regular = { ...note("a".repeat(32), "Recent"), updatedAt: 20, folder: "Projects/OSL" }; const pinned = { ...note("b".repeat(32), "Pinned"), pinned: true, updatedAt: 2 }; expect(filteredNotes([regular, pinned], "", "all").map((item) => item.title)).toEqual(["Pinned", "Recent"]); const markup = notesWorkspaceMarkup({ notes: [regular, pinned], activeId: pinned.id, query: "", filter: "all", mode: "edit", loading: false, loadError: "", saveState: "saved", developerOpen: false, commandOpen: true, createOpen: false }); expect(markup).toContain('style="--folder-depth:1"'); expect(markup).toContain("Find a file or command"); expect(markup).toContain("Unpin current file"); });
  it("builds wiki links and backlinks", () => { const target = note("a".repeat(32), "Project"); const source = note("b".repeat(32), "Source", "See [[Project]] and [[Project]]"); expect(wikiLinks(source.body)).toEqual(["Project"]); expect(backlinksFor([target, source], target)).toEqual([source]); });
  it("builds an escaped local-only knowledge graph and template surface", () => { const target = note("a".repeat(32), "Project <safe>"); const source = note("b".repeat(32), "Source", "See [[Project <safe>]]"); const graph = knowledgeGraphMarkup([target, source]); expect(graph).toContain("2 notes and 1 links"); expect(graph).toContain("&lt;safe&gt;"); expect(graph).not.toContain("Project <safe>"); expect(graph).toContain('data-note-template="research"'); expect(graph).not.toContain("http"); });
  it("indexes bounded cross-note tasks with due dates, priorities, and recurrence", () => { const source = note("a".repeat(32), "Plan", "- [ ] Ship safely 📅 2026-07-23 ⏫ 🔁 every week\n- [x] Verify\nnot a task"); const tasks = noteTasks([source]); expect(tasks).toEqual([{ noteId: source.id, noteTitle: "Plan", line: 0, text: "Ship safely 📅 2026-07-23 ⏫ 🔁 every week", completed: false, due: "2026-07-23", priority: "high", recurrence: "weekly" }, { noteId: source.id, noteTitle: "Plan", line: 1, text: "Verify", completed: true, due: null, priority: "normal", recurrence: null }]); const markup = taskDashboardMarkup([source]); expect(markup).toContain(`data-task-toggle="${source.id}:0"`); expect(markup).toContain("high priority"); expect(markup).toContain("repeats weekly"); expect(markup).not.toContain("http"); });
  it("preserves completed recurring occurrences and advances dates exactly once", () => { const weekly = "- [ ] Review 📅 2026-07-23 🔁 every week"; expect(toggleTaskMarkdownLine(weekly)).toEqual({ lines: ["- [x] Review 📅 2026-07-23 🔁 every week", "- [ ] Review 📅 2026-07-30 🔁 every week"], rescheduled: true }); expect(toggleTaskMarkdownLine(weekly, "- [ ] Review 📅 2026-07-30 🔁 every week")).toEqual({ lines: ["- [x] Review 📅 2026-07-23 🔁 every week"], rescheduled: true }); expect(toggleTaskMarkdownLine("- [ ] Close books 📅 2026-01-31 🔁 every month")?.lines[1]).toContain("2026-02-28"); expect(toggleTaskMarkdownLine("- [ ] Leap review 📅 2024-02-29 🔁 every year")?.lines[1]).toContain("2025-02-28"); expect(toggleTaskMarkdownLine("- [ ] Invalid 📅 2026-02-31 🔁 every month")).toEqual({ lines: ["- [x] Invalid 📅 2026-02-31 🔁 every month"], rescheduled: false }); });
  it("builds local typed table, board, and calendar property views", () => {
    const source = note("a".repeat(32), "Plan <safe>", '---\nStatus: "Doing"\nDue: 2026-07-31\n---\nPrivate body');
    const table = propertiesDashboardMarkup([source], "table"); const board = propertiesDashboardMarkup([source], "board", "Status"); const calendar = propertiesDashboardMarkup([source], "calendar", "Due");
    expect(table).toContain("Plan &lt;safe&gt;"); expect(table).not.toContain("Plan <safe>"); expect(board).toContain("Doing"); expect(calendar).toContain("2026-07-31");
    expect(`${table}${board}${calendar}`).not.toContain("http");
  });
  it("escapes HTML in preview", () => { const preview = markdownPreview("# Hi\n<script>alert(1)</script>\n**bold**"); expect(preview).not.toContain("<script>"); expect(preview).toContain("&lt;script&gt;"); expect(preview).toContain("<strong>bold</strong>"); });
  it("renders a bounded inert Markdown table, callout, math, and language fence", () => { const preview = markdownPreview("| Name | Value |\n| --- | ---: |\n| <safe> | ==yes== |\n> [!WARNING] Local only\n> Never upload\nInline $x + y$\n```ts\nconst x = '<safe>'\n```"); expect(preview).toContain("<table>"); expect(preview).toContain("&lt;safe&gt;"); expect(preview).not.toContain("<safe>"); expect(preview).toContain("type-warning"); expect(preview).toContain('class="preview-math"'); expect(preview).toContain('data-language="ts"'); });
  it("exposes discoverable local workspace shortcuts", () => { const markup = notesWorkspaceMarkup({ notes: [note("a".repeat(32), "Current")], activeId: "a".repeat(32), query: "", filter: "all", mode: "edit", loading: false, loadError: "", saveState: "saved", developerOpen: false, createOpen: false, historyOpen: false }); expect(markup).toContain("Keyboard shortcuts"); expect(markup).toContain("Ctrl/⌘ K"); expect(markup).toContain("Graph / tasks"); });
  it("renders only bounded encrypted attachment receipts and labels exact metadata-preserving export", () => {
    const attachment = { id: "c".repeat(32), name: "field <notes>.pdf", mime: "application/pdf", size: 2048, chunkCount: 1, createdAt: 4 };
    const markup = notesWorkspaceMarkup({ notes: [note("a".repeat(32), "Current")], activeId: "a".repeat(32), query: "", filter: "all", mode: "edit", loading: false, loadError: "", saveState: "saved", developerOpen: false, createOpen: false, attachments: [attachment] });
    expect(markup).toContain("Local and encrypted"); expect(markup).toContain("field &lt;notes&gt;.pdf"); expect(markup).not.toContain("field <notes>.pdf");
    expect(markup).toContain(`data-note-attachment-export="${attachment.id}"`); expect(markup).toContain("Export exact original"); expect(markup).toContain("including metadata");
  });
  it("strictly parses and renders encrypted version history", () => {
    const revision: OslNoteRevision = { id: "b".repeat(32), noteId: "a".repeat(32), kind: "note", title: "Earlier", body: "Private draft", folder: "Work", tags: ["idea"], favorite: false, pinned: false, createdAt: 3 };
    expect(parseOslNoteRevision(revision)).toEqual(revision);
    expect(parseOslNoteRevision({ ...revision, remoteUrl: "https://example.com" })).toBeNull();
    const markup = notesWorkspaceMarkup({ notes: [note("a".repeat(32), "Current")], activeId: "a".repeat(32), query: "", filter: "all", mode: "edit", loading: false, loadError: "", saveState: "saved", developerOpen: false, createOpen: false, historyOpen: true, revisions: [revision], selectedRevisionId: revision.id });
    expect(markup).toContain("Version history"); expect(markup).toContain('data-note-history-restore="bbbb'); expect(markup).toContain("Previewing encrypted snapshot"); expect(markup).toContain("Private draft"); expect(markup).toContain("Text changed"); expect(markup).toContain("Restore text and properties"); expect(markup).toContain("current attachment set stays unchanged");
  });
});
