import { invoke } from "@tauri-apps/api/core";
import { isTauriRuntime } from "./preferences";

export const OSL_ASSET_MAX_BYTES = 8 * 1024 * 1024 * 1024;
export interface OslAssetDescriptor { id: string; name: string; mime: string; size: number; chunkCount: number; createdAt: number; }
export interface OslAssetUpload { asset: OslAssetDescriptor; chunkBytes: number; nextChunk: number; }
export interface OslCreativeAdjustments { brightness: number; contrast: number; saturation: number; blur: number; rotate: number; playbackRate: number; }
export interface OslCreativeMask { enabled: boolean; inverted: boolean; feather: number; }
export interface OslCreativeLayer { id: string; type: "source" | "adjustment"; name: string; assetId: string | null; visible: boolean; opacity: number; blendMode: "normal" | "multiply" | "screen" | "overlay" | "darken" | "lighten"; adjustments: OslCreativeAdjustments; mask: OslCreativeMask; }
export interface OslTimelineClip { id: string; assetId: string; name: string; start: number; inPoint: number; duration: number; speed: number; volume: number; fadeIn: number; fadeOut: number; }
export interface OslTimelineTrack { id: string; name: string; kind: "video" | "audio" | "motion"; muted: boolean; locked: boolean; clips: OslTimelineClip[]; }
export interface OslTimelineWorkspace { kind: "timeline"; duration: number; playhead: number; selectedTrackId: string; tracks: OslTimelineTrack[]; }
export interface OslSceneNode { id: string; name: string; type: "mesh" | "camera" | "light" | "empty"; visible: boolean; locked: boolean; position: [number, number, number]; rotation: [number, number, number]; scale: [number, number, number]; material: string; }
export interface OslSceneWorkspace { kind: "scene"; selectedNodeId: string; nodes: OslSceneNode[]; }
export type OslCreativeWorkspace = { kind: "photo" } | { kind: "asset" } | OslTimelineWorkspace | OslSceneWorkspace;
export interface OslCreativeProject { format: "osl-creative-project-v3"; assetId: string; name: string; mime: string; size: number; editor: "photo" | "video" | "audio" | "model3d" | "asset"; adjustments: OslCreativeAdjustments; layers: OslCreativeLayer[]; selectedLayerId: string | null; workspace: OslCreativeWorkspace; }

const record = (value: unknown): value is Record<string, unknown> => typeof value === "object" && value !== null && !Array.isArray(value);
export function parseOslAssetDescriptor(value: unknown): OslAssetDescriptor | null {
  if (!record(value) || Object.keys(value).length !== 6 || !["id", "name", "mime", "size", "chunkCount", "createdAt"].every((key) => Object.hasOwn(value, key)) || typeof value.id !== "string" || !/^[a-f0-9]{32}$/u.test(value.id) || typeof value.name !== "string" || !value.name || value.name.length > 240 || typeof value.mime !== "string" || !/^[a-z0-9.+-]+\/[a-z0-9.+-]+$/u.test(value.mime) || !Number.isSafeInteger(value.size) || Number(value.size) <= 0 || Number(value.size) > OSL_ASSET_MAX_BYTES || !Number.isSafeInteger(value.chunkCount) || Number(value.chunkCount) <= 0 || !Number.isSafeInteger(value.createdAt) || Number(value.createdAt) <= 0) return null;
  return value as unknown as OslAssetDescriptor;
}
export function parseOslAssetUpload(value: unknown): OslAssetUpload | null { if (!record(value) || Object.keys(value).length !== 3 || !Object.hasOwn(value, "asset") || !Object.hasOwn(value, "chunkBytes") || !Object.hasOwn(value, "nextChunk") || !Number.isSafeInteger(value.chunkBytes) || Number(value.chunkBytes) !== 256 * 1024 || !Number.isSafeInteger(value.nextChunk) || Number(value.nextChunk) < 0) return null; const asset = parseOslAssetDescriptor(value.asset); return asset && Number(value.nextChunk) <= asset.chunkCount ? { asset, chunkBytes: Number(value.chunkBytes), nextChunk: Number(value.nextChunk) } : null; }

export async function listOslAssets(): Promise<OslAssetDescriptor[] | null> { if (!isTauriRuntime()) return null; const raw = await invoke("list_osl_assets"); if (!Array.isArray(raw) || raw.length > 10_000) return null; const assets = raw.map(parseOslAssetDescriptor); return assets.some((asset) => !asset) ? null : assets as OslAssetDescriptor[]; }
export async function listOslAssetsForProject(noteId: string): Promise<OslAssetDescriptor[] | null> { if (!isTauriRuntime() || !/^[a-f0-9]{32}$/u.test(noteId)) return null; const raw = await invoke("list_osl_assets_for_project", { noteId }); if (!Array.isArray(raw) || raw.length > 128) return null; const assets = raw.map(parseOslAssetDescriptor); return assets.some((asset) => !asset) ? null : assets as OslAssetDescriptor[]; }

export async function uploadOslAsset(file: File, progress?: (completed: number, total: number) => void): Promise<OslAssetDescriptor | null> {
  if (!isTauriRuntime() || file.size <= 0 || file.size > OSL_ASSET_MAX_BYTES) return null;
  const fallbackMime = "application/octet-stream"; const mime = /^[a-z0-9.+-]+\/[a-z0-9.+-]+$/u.test(file.type) ? file.type : fallbackMime;
  const upload = parseOslAssetUpload(await invoke("begin_osl_asset_upload", { name: file.name, mime, size: file.size })); if (!upload) return null;
  for (let index = upload.nextChunk; index < upload.asset.chunkCount; index += 1) {
    const start = index * upload.chunkBytes; const bytes = [...new Uint8Array(await file.slice(start, Math.min(file.size, start + upload.chunkBytes)).arrayBuffer())];
    if (await invoke("append_osl_asset_chunk", { assetId: upload.asset.id, index, bytes }) !== index + 1) return null;
    progress?.(index + 1, upload.asset.chunkCount);
  }
  return parseOslAssetDescriptor(await invoke("finish_osl_asset_upload", { assetId: upload.asset.id }));
}

export async function cancelOslAssetUpload(assetId: string): Promise<boolean> { return isTauriRuntime() && /^[a-f0-9]{32}$/u.test(assetId) && await invoke("cancel_osl_asset_upload", { assetId }) === true; }
export async function linkOslAssetProject(assetId: string, noteId: string): Promise<boolean> { return isTauriRuntime() && /^[a-f0-9]{32}$/u.test(assetId) && /^[a-f0-9]{32}$/u.test(noteId) && await invoke("link_osl_asset_project", { assetId, noteId }) === true; }
export async function releaseOslAssetProject(assetId: string, noteId: string): Promise<boolean> { return isTauriRuntime() && /^[a-f0-9]{32}$/u.test(assetId) && /^[a-f0-9]{32}$/u.test(noteId) && await invoke("release_osl_asset_project", { assetId, noteId }) === true; }
export async function releaseOslAssetsForProject(noteId: string): Promise<number | null> {
  if (!isTauriRuntime() || !/^[a-f0-9]{32}$/u.test(noteId)) return null;
  const released = await invoke("release_osl_assets_for_project", { noteId });
  return Number.isSafeInteger(released) && Number(released) >= 0 ? Number(released) : null;
}
export async function discardUnreferencedOslAsset(assetId: string): Promise<boolean> { return isTauriRuntime() && /^[a-f0-9]{32}$/u.test(assetId) && await invoke("discard_unreferenced_osl_asset", { assetId }) === true; }

export async function readOslAssetBlob(asset: OslAssetDescriptor, maximumBytes = 64 * 1024 * 1024): Promise<Blob | null> {
  if (!isTauriRuntime() || asset.size > maximumBytes) return null;
  const chunks: ArrayBuffer[] = []; let total = 0;
  for (let index = 0; index < asset.chunkCount; index += 1) { const raw = await invoke("read_osl_asset_chunk", { assetId: asset.id, index }); if (!Array.isArray(raw) || raw.length > 256 * 1024 || !raw.every((byte) => Number.isInteger(byte) && byte >= 0 && byte <= 255)) return null; const chunk = new ArrayBuffer(raw.length); new Uint8Array(chunk).set(raw); total += chunk.byteLength; if (total > asset.size) return null; chunks.push(chunk); }
  return total === asset.size ? new Blob(chunks, { type: asset.mime }) : null;
}

const adjustmentKeys = ["brightness", "contrast", "saturation", "blur", "rotate", "playbackRate"];
const defaultAdjustments = (): OslCreativeAdjustments => ({ brightness: 100, contrast: 100, saturation: 100, blur: 0, rotate: 0, playbackRate: 1 });
function parseAdjustments(value: unknown): OslCreativeAdjustments | null { if (!record(value) || Object.keys(value).length !== adjustmentKeys.length || !adjustmentKeys.every((key) => Object.hasOwn(value, key))) return null; if (![value.brightness, value.contrast, value.saturation].every((item) => typeof item === "number" && Number.isFinite(item) && item >= 0 && item <= 200) || typeof value.blur !== "number" || value.blur < 0 || value.blur > 20 || typeof value.rotate !== "number" || value.rotate < -180 || value.rotate > 180 || typeof value.playbackRate !== "number" || value.playbackRate < .25 || value.playbackRate > 4) return null; return value as unknown as OslCreativeAdjustments; }
function parseLayer(value: unknown): OslCreativeLayer | null { if (!record(value) || Object.keys(value).length !== 9 || !["id", "type", "name", "assetId", "visible", "opacity", "blendMode", "adjustments", "mask"].every((key) => Object.hasOwn(value, key)) || typeof value.id !== "string" || !/^[a-z0-9]{4,20}$/u.test(value.id) || !["source", "adjustment"].includes(String(value.type)) || typeof value.name !== "string" || !value.name || value.name.length > 80 || value.assetId !== null && (typeof value.assetId !== "string" || !/^[a-f0-9]{32}$/u.test(value.assetId)) || value.type === "source" && value.assetId === null || value.type === "adjustment" && value.assetId !== null || typeof value.visible !== "boolean" || typeof value.opacity !== "number" || value.opacity < 0 || value.opacity > 100 || !["normal", "multiply", "screen", "overlay", "darken", "lighten"].includes(String(value.blendMode)) || !record(value.mask) || Object.keys(value.mask).length !== 3 || typeof value.mask.enabled !== "boolean" || typeof value.mask.inverted !== "boolean" || typeof value.mask.feather !== "number" || value.mask.feather < 0 || value.mask.feather > 100) return null; const adjustments = parseAdjustments(value.adjustments); return adjustments ? { ...value, adjustments } as unknown as OslCreativeLayer : null; }
const boundedNumber = (value: unknown, minimum: number, maximum: number): value is number => typeof value === "number" && Number.isFinite(value) && value >= minimum && value <= maximum;
function defaultWorkspace(editor: OslCreativeProject["editor"], assetId: string, name: string): OslCreativeWorkspace { if (editor === "photo") return { kind: "photo" }; if (editor === "asset") return { kind: "asset" }; if (editor === "model3d") return { kind: "scene", selectedNodeId: "source1", nodes: [{ id: "source1", name: name.slice(0, 80), type: "mesh", visible: true, locked: false, position: [0, 0, 0], rotation: [0, 0, 0], scale: [1, 1, 1], material: "Default" }] }; const trackKind = editor === "video" ? "video" : "audio"; return { kind: "timeline", duration: 0, playhead: 0, selectedTrackId: "track1", tracks: [{ id: "track1", name: editor === "video" ? "Video 1" : "Audio 1", kind: trackKind, muted: false, locked: false, clips: [{ id: "sourceclip", assetId, name: name.slice(0, 80), start: 0, inPoint: 0, duration: 0, speed: 1, volume: 100, fadeIn: 0, fadeOut: 0 }] }] }; }
function parseWorkspace(value: unknown, editor: OslCreativeProject["editor"], assetId: string): OslCreativeWorkspace | null {
  if (!record(value) || typeof value.kind !== "string") return null; if (value.kind === "photo" || value.kind === "asset") return Object.keys(value).length === 1 && value.kind === (editor === "photo" ? "photo" : editor === "asset" ? "asset" : "") ? value as OslCreativeWorkspace : null;
  if (value.kind === "timeline") { if (!["video", "audio"].includes(editor) || Object.keys(value).length !== 5 || !boundedNumber(value.duration, 0, 604_800) || !boundedNumber(value.playhead, 0, Number(value.duration)) || typeof value.selectedTrackId !== "string" || !Array.isArray(value.tracks) || value.tracks.length < 1 || value.tracks.length > 64) return null; const tracks = value.tracks as unknown[]; if (!tracks.every((track) => record(track) && Object.keys(track).length === 6 && typeof track.id === "string" && /^[a-z0-9]{4,20}$/u.test(track.id) && typeof track.name === "string" && track.name.length > 0 && track.name.length <= 80 && ["video", "audio", "motion"].includes(String(track.kind)) && typeof track.muted === "boolean" && typeof track.locked === "boolean" && Array.isArray(track.clips) && track.clips.length <= 512 && track.clips.every((clip) => record(clip) && Object.keys(clip).length === 10 && typeof clip.id === "string" && /^[a-z0-9]{4,20}$/u.test(clip.id) && clip.assetId === assetId && typeof clip.name === "string" && clip.name.length > 0 && clip.name.length <= 80 && boundedNumber(clip.start, 0, 604_800) && boundedNumber(clip.inPoint, 0, 604_800) && boundedNumber(clip.duration, 0, 604_800) && boundedNumber(clip.speed, .25, 4) && boundedNumber(clip.volume, 0, 200) && boundedNumber(clip.fadeIn, 0, 3_600) && boundedNumber(clip.fadeOut, 0, 3_600)))) return null; if (!tracks.some((track) => record(track) && track.id === value.selectedTrackId) || new Set(tracks.map((track) => (track as Record<string, unknown>).id)).size !== tracks.length) return null; return value as unknown as OslTimelineWorkspace; }
  if (value.kind === "scene") { if (editor !== "model3d" || Object.keys(value).length !== 3 || typeof value.selectedNodeId !== "string" || !Array.isArray(value.nodes) || value.nodes.length < 1 || value.nodes.length > 2_000) return null; const nodes = value.nodes as unknown[]; if (!nodes.every((node) => record(node) && Object.keys(node).length === 9 && typeof node.id === "string" && /^[a-z0-9]{4,20}$/u.test(node.id) && typeof node.name === "string" && node.name.length > 0 && node.name.length <= 80 && ["mesh", "camera", "light", "empty"].includes(String(node.type)) && typeof node.visible === "boolean" && typeof node.locked === "boolean" && [node.position, node.rotation, node.scale].every((vector) => Array.isArray(vector) && vector.length === 3 && vector.every((number) => boundedNumber(number, -1_000_000, 1_000_000))) && (node.scale as number[]).every((number) => number > 0) && typeof node.material === "string" && node.material.length <= 80)) return null; if (!nodes.some((node) => record(node) && node.id === value.selectedNodeId) || new Set(nodes.map((node) => (node as Record<string, unknown>).id)).size !== nodes.length) return null; return value as unknown as OslSceneWorkspace; }
  return null;
}
export function parseOslCreativeProject(body: string): OslCreativeProject | null {
  try {
    const value = JSON.parse(body) as unknown; if (!record(value)) return null;
    if (typeof value.assetId !== "string" || !/^[a-f0-9]{32}$/u.test(value.assetId) || typeof value.name !== "string" || value.name.length < 1 || value.name.length > 240 || typeof value.mime !== "string" || !/^[a-z0-9.+-]+\/[a-z0-9.+-]+$/u.test(value.mime) || !Number.isSafeInteger(value.size) || Number(value.size) <= 0 || !["photo", "video", "audio", "model3d", "asset"].includes(String(value.editor))) return null;
    const adjustments = parseAdjustments(value.adjustments); if (!adjustments) return null;
    const assetId = value.assetId; const name = value.name; const mime = value.mime; const editor = value.editor as OslCreativeProject["editor"];
    if (value.format === "osl-creative-project-v1" && Object.keys(value).length === 7) { const source: OslCreativeLayer | null = editor === "photo" ? { id: "source1", type: "source", name: "Original", assetId, visible: true, opacity: 100, blendMode: "normal", adjustments, mask: { enabled: false, inverted: false, feather: 0 } } : null; return { format: "osl-creative-project-v3", assetId, name, mime, size: Number(value.size), editor, adjustments, layers: source ? [source] : [], selectedLayerId: source?.id ?? null, workspace: defaultWorkspace(editor, assetId, name) }; }
    if (!["osl-creative-project-v2", "osl-creative-project-v3"].includes(String(value.format)) || ![9, 10].includes(Object.keys(value).length) || !Array.isArray(value.layers) || value.layers.length > 64 || value.selectedLayerId !== null && typeof value.selectedLayerId !== "string") return null;
    const layers = value.layers.map(parseLayer); if (layers.some((layer) => !layer)) return null; const typed = layers as OslCreativeLayer[]; if (new Set(typed.map((layer) => layer.id)).size !== typed.length || value.selectedLayerId !== null && !typed.some((layer) => layer.id === value.selectedLayerId) || typed.some((layer) => layer.assetId !== null && layer.assetId !== assetId)) return null;
    const workspace = value.format === "osl-creative-project-v3" ? parseWorkspace(value.workspace, editor, assetId) : defaultWorkspace(editor, assetId, name); if (!workspace) return null;
    return { format: "osl-creative-project-v3", assetId, name, mime, size: Number(value.size), editor, adjustments, layers: typed, selectedLayerId: value.selectedLayerId as string | null, workspace };
  } catch { return null; }
}

export function assetIdFromCatalogBody(body: string): string | null { return parseOslCreativeProject(body)?.assetId ?? /^Encrypted creative asset\n\n(?:[^\n]*\n){3}Asset: osl-asset:([a-f0-9]{32})\n/u.exec(body)?.[1] ?? null; }

export function assetCatalogBody(asset: OslAssetDescriptor): string { const extension = asset.name.toLowerCase().split(".").pop() ?? ""; const editor: OslCreativeProject["editor"] = asset.mime.startsWith("image/") ? "photo" : asset.mime.startsWith("video/") ? "video" : asset.mime.startsWith("audio/") ? "audio" : ["glb", "gltf", "obj", "fbx", "usd", "usdz", "stl", "ply", "abc"].includes(extension) ? "model3d" : "asset"; const adjustments = defaultAdjustments(); const source: OslCreativeLayer[] = editor === "photo" ? [{ id: "source1", type: "source", name: "Original", assetId: asset.id, visible: true, opacity: 100, blendMode: "normal", adjustments: defaultAdjustments(), mask: { enabled: false, inverted: false, feather: 0 } }] : []; return JSON.stringify({ format: "osl-creative-project-v3", assetId: asset.id, name: asset.name, mime: asset.mime, size: asset.size, editor, adjustments, layers: source, selectedLayerId: source[0]?.id ?? null, workspace: defaultWorkspace(editor, asset.id, asset.name) } satisfies OslCreativeProject); }
