import { invoke } from "@tauri-apps/api/core";
import { isTauriRuntime } from "./preferences";
import type { OslDocumentKind, OslNote } from "./osl-notes";

export interface OslSharedDocument { kind: OslDocumentKind; title: string; body: string; folder: string; tags: string[]; favorite: boolean; }
export interface OslLanInvitation { code: string; address: string; roomId: string; encrypted: true; requiresCloud: false; requiresPro: false; }
export interface OslLanSession { sessionId: string; role: "host" | "guest"; revision: number; document: OslSharedDocument; invitation: OslLanInvitation | null; connected: true; encrypted: true; cloud: false; }
export interface OslLanSync { revision: number; document: OslSharedDocument; changed: boolean; conflict: boolean; connected: boolean; }

const kinds = new Set(["note", "document", "spreadsheet", "drawing", "presentation", "photo", "video", "audio", "model3d"]);
const record = (value: unknown): value is Record<string, unknown> => typeof value === "object" && value !== null && !Array.isArray(value);
const exact = (value: Record<string, unknown>, keys: string[]) => Object.keys(value).length === keys.length && keys.every((key) => Object.hasOwn(value, key));
export function parseSharedDocument(value: unknown): OslSharedDocument | null { if (!record(value) || !exact(value, ["kind", "title", "body", "folder", "tags", "favorite"]) || !kinds.has(String(value.kind)) || typeof value.title !== "string" || new TextEncoder().encode(value.title).byteLength > 240 || typeof value.body !== "string" || new TextEncoder().encode(value.body).byteLength > 256 * 1024 || typeof value.folder !== "string" || new TextEncoder().encode(value.folder).byteLength > 80 || !Array.isArray(value.tags) || value.tags.length > 16 || !value.tags.every((tag) => typeof tag === "string" && tag.length > 0 && new TextEncoder().encode(tag).byteLength <= 32) || typeof value.favorite !== "boolean") return null; return value as unknown as OslSharedDocument; }
export function sharedDocument(note: OslNote): OslSharedDocument { return { kind: note.kind, title: note.title, body: note.body, folder: note.folder, tags: [...note.tags], favorite: note.favorite }; }
function parseInvitation(value: unknown): OslLanInvitation | null { if (!record(value) || !exact(value, ["code", "address", "roomId", "encrypted", "requiresCloud", "requiresPro"]) || typeof value.code !== "string" || value.code.length > 256 || typeof value.address !== "string" || typeof value.roomId !== "string" || !/^[a-f0-9]{32}$/u.test(value.roomId) || value.encrypted !== true || value.requiresCloud !== false || value.requiresPro !== false) return null; return value as unknown as OslLanInvitation; }
export function parseLanSession(value: unknown): OslLanSession | null { if (!record(value) || !exact(value, ["sessionId", "role", "revision", "document", "invitation", "connected", "encrypted", "cloud"]) || typeof value.sessionId !== "string" || !/^[a-f0-9]{32}$/u.test(value.sessionId) || !["host", "guest"].includes(String(value.role)) || !Number.isSafeInteger(value.revision) || Number(value.revision) < 0 || value.connected !== true || value.encrypted !== true || value.cloud !== false) return null; const document = parseSharedDocument(value.document); const invitation = value.invitation === null ? null : parseInvitation(value.invitation); if (!document || value.invitation !== null && !invitation || value.role === "host" && !invitation || value.role === "guest" && invitation) return null; return { sessionId: value.sessionId, role: value.role as "host" | "guest", revision: Number(value.revision), document, invitation, connected: true, encrypted: true, cloud: false }; }
export function parseLanSync(value: unknown): OslLanSync | null { if (!record(value) || !exact(value, ["revision", "document", "changed", "conflict", "connected"]) || !Number.isSafeInteger(value.revision) || Number(value.revision) < 0 || typeof value.changed !== "boolean" || typeof value.conflict !== "boolean" || typeof value.connected !== "boolean") return null; const document = parseSharedDocument(value.document); return document ? { revision: Number(value.revision), document, changed: value.changed, conflict: value.conflict, connected: value.connected } : null; }

export async function hostOslLanRoom(document: OslSharedDocument): Promise<OslLanSession | null> { if (!isTauriRuntime() || !parseSharedDocument(document)) return null; return parseLanSession(await invoke("host_osl_lan_room", { document })); }
export async function joinOslLanRoom(code: string): Promise<OslLanSession | null> { if (!isTauriRuntime() || !code || code.length > 256) return null; return parseLanSession(await invoke("join_osl_lan_room", { code })); }
export async function syncOslLanRoom(session: OslLanSession, document?: OslSharedDocument): Promise<OslLanSync | null> { if (!isTauriRuntime() || document && !parseSharedDocument(document)) return null; const command = session.role === "host" ? "sync_hosted_osl_lan_room" : "sync_joined_osl_lan_room"; const identity = session.role === "host" ? { roomId: session.sessionId } : { sessionId: session.sessionId }; return parseLanSync(await invoke(command, { ...identity, baseRevision: session.revision, document: document ?? null })); }
export async function stopOslLanRoom(sessionId: string): Promise<boolean> { return isTauriRuntime() && /^[a-f0-9]{32}$/u.test(sessionId) && await invoke("stop_osl_lan_room", { sessionId }) === true; }
