import { describe, expect, it } from "vitest";
import { importWorkspaceText, textImportReceiptFile } from "./osl-import";
import { parseDrawing, parseSheet } from "./osl-office";
describe("local-only OSL workspace imports", () => {
  it("imports quoted CSV into a bounded spreadsheet", () => { const imported = importWorkspaceText("budget.csv", 'Name,Amount\n"Hosting, private",12'); expect(imported?.kind).toBe("spreadsheet"); expect(parseSheet(imported?.body ?? "")?.cells["1:0"]).toBe("Hosting, private"); });
  it("imports safe SVG primitives and rejects active content", () => { const imported = importWorkspaceText("diagram.svg", '<svg><rect x="10" y="20" width="80" height="40" fill="#06b6d4"/></svg>'); expect(parseDrawing(imported?.body ?? "")?.items).toHaveLength(1); expect(importWorkspaceText("bad.svg", '<svg><script>alert(1)</script></svg>')).toBeNull(); });
  it("maps text formats without network conversion", () => { expect(importWorkspaceText("idea.md", "# Private")?.kind).toBe("note"); expect(importWorkspaceText("letter.txt", "Hello")?.kind).toBe("document"); expect(importWorkspaceText("unknown.psd", "data")).toBeNull(); });
  it("imports inert HTML and RTF text while rejecting active or embedded content", () => { expect(importWorkspaceText("page.html", "<!doctype html><html><body><h1>Local</h1><p>Private &amp; safe</p></body></html>")?.body).toBe("Local\nPrivate & safe"); expect(importWorkspaceText("active.html", '<html><body><img src="https://example.test/tracker"></body></html>')).toBeNull(); expect(importWorkspaceText("letter.rtf", "{\\rtf1\\ansi Hello\\par Private}")?.body).toBe("Hello\nPrivate"); expect(importWorkspaceText("embedded.rtf", "{\\rtf1{\\object bad}}" )).toBeNull(); });
  it("describes lossy text conversions in a sanitized encrypted receipt", () => { const imported = importWorkspaceText("page.html", "<html><body><p>Private</p></body></html>")!; const receipt = textImportReceiptFile(imported, "<draft>\npage.html")!; expect(receipt).toMatchObject({ kind: "note", folder: "Imports", tags: ["import-receipt", "html"] }); expect(receipt.body).toContain("draft page.html"); expect(receipt.body).toContain("Page layout, styles, links, images"); expect(receipt.body).not.toContain("<draft>"); expect(textImportReceiptFile(imported, "plain.txt")).toBeNull(); });
  it("rejects oversized text instead of silently truncating it", () => { expect(importWorkspaceText("archive.md", "x".repeat(256 * 1024 + 1))).toBeNull(); });
  it("imports metadata-stripped portable projects without recreating private organization", () => { const imported = importWorkspaceText("private.osl.json", JSON.stringify({ format: "osl-workspace-file-v2", privacy: { metadataStripped: true }, kind: "note", title: "Shared", body: "Only the content" })); expect(imported).toMatchObject({ kind: "note", folder: "", tags: [] }); });
});
