import { describe, expect, it } from "vitest";
import { assetCatalogBody, assetIdFromCatalogBody, parseOslAssetDescriptor, parseOslAssetUpload, parseOslCreativeProject, releaseOslAssetsForProject } from "./osl-assets";
const asset = { id: "a".repeat(32), name: "photo.psd", mime: "image/vnd.adobe.photoshop", size: 300000, chunkCount: 2, createdAt: 1 };
describe("encrypted creative asset boundary", () => {
  it("strictly parses bounded native asset receipts", () => { expect(parseOslAssetDescriptor(asset)).toEqual(asset); expect(parseOslAssetDescriptor({ ...asset, url: "https://example.com" })).toBeNull(); expect(parseOslAssetUpload({ asset, chunkBytes: 262144, nextChunk: 1 })?.asset).toEqual(asset); });
  it("creates a bounded creative project without embedding source bytes", () => { const body = assetCatalogBody(asset); expect(assetIdFromCatalogBody(body)).toBe(asset.id); expect(parseOslCreativeProject(body)?.editor).toBe("photo"); expect(body).not.toContain("data:"); });
  it("migrates legacy photo adjustments into a source layer", () => { const adjustments = { brightness: 90, contrast: 110, saturation: 100, blur: 0, rotate: 0, playbackRate: 1 }; const project = parseOslCreativeProject(JSON.stringify({ format: "osl-creative-project-v1", assetId: asset.id, name: asset.name, mime: asset.mime, size: asset.size, editor: "photo", adjustments })); expect(project?.format).toBe("osl-creative-project-v3"); expect(project?.layers).toHaveLength(1); expect(project?.layers[0].adjustments).toEqual(adjustments); });
  it("creates bounded timeline and 3D scene workspaces", () => { const video = { ...asset, name: "clip.mp4", mime: "video/mp4" }; const timeline = parseOslCreativeProject(assetCatalogBody(video)); expect(timeline?.workspace.kind).toBe("timeline"); if (timeline?.workspace.kind === "timeline") { timeline.workspace.tracks[0].clips[0].volume = 201; expect(parseOslCreativeProject(JSON.stringify(timeline))).toBeNull(); } const model = { ...asset, name: "scene.glb", mime: "model/gltf-binary" }; const scene = parseOslCreativeProject(assetCatalogBody(model)); expect(scene?.workspace.kind).toBe("scene"); });
  it("strictly bounds layers and keeps every source inside the encrypted project", () => { const project = parseOslCreativeProject(assetCatalogBody(asset))!; const layer = { ...project.layers[0], id: "adjust1", type: "adjustment" as const, assetId: null, name: "Contrast" }; project.layers.push(layer); project.selectedLayerId = layer.id; expect(parseOslCreativeProject(JSON.stringify(project))?.layers).toHaveLength(2); project.layers[0].assetId = "b".repeat(32); expect(parseOslCreativeProject(JSON.stringify(project))).toBeNull(); project.layers = Array.from({ length: 65 }, (_, index) => ({ ...layer, id: `layer${index.toString(36).padStart(2, "0")}` })); expect(parseOslCreativeProject(JSON.stringify(project))).toBeNull(); });
  it("rejects invalid project ids before invoking native cleanup", async () => { expect(await releaseOslAssetsForProject("not-an-id")).toBeNull(); });
});
