/**
 * TASK 0853 — the data behind one tile's status route.
 *
 * TASK 0852 gave every connected-app row a generated status page: the real
 * capability, the generated label, and the sentence that justifies it, all
 * derived in `claim_state.rs` from the same facts that decide the tile label.
 * That data stopped at the catalog. The route a person actually opens when they
 * tap a tile still had to say something, and what a route says when nobody has
 * connected it to the generated data is a sentence somebody typed — which is
 * where "Coming soon" came from in the first place.
 *
 * This module is the connection. It turns one `NativeApp` into the data its
 * status route shows, and it is deliberately incapable of inventing prose:
 *
 *   - the label, the capability and the explanation are copied BYTE FOR BYTE
 *     from `app.statusPage`, which the backend generated;
 *   - everything else the route says comes from {@link TILE_STATUS_AUTHORED_TEXT},
 *     a closed list of four strings, each naming an action that works today and
 *     is reached by a handler that already exists (`[data-home-app]` opens the
 *     app, `[data-route]` navigates);
 *   - {@link auditTileStatusRoute} separates those two groups again and reports
 *     every future promise it finds in either, so the check in
 *     `tile-status-route.test.ts` reads the route data rather than the screen.
 *
 * WHY THE AUDIT SPLITS GENERATED FROM HAND-WRITTEN. "Coming later" is a future
 * promise by any reading, and it is also the generated label for `comingSoon`
 * (TASK 0804), which TASK 0854 requires this route to agree with exactly. The
 * audit therefore permits that phrase in exactly one place: a `generatedLabel`
 * that still equals `nativeAppGeneratedLabel(app.supportStatus)`. Type a label
 * by hand — or let one drift from the status it is supposed to render — and it
 * stops counting as generated, lands in the hand-written pile, and the promise
 * inside it is reported. That is the whole point: the route cannot promise
 * anything the claim table did not generate.
 */

import { nativeAppGeneratedLabel, type NativeApp, type NativeAppId } from "./services";

/** Where a status-route action goes. Every one of these routes exists today. */
export type TileStatusRouteTarget = "service" | "osl-chat" | "connections" | "home";

/** How the action is reached in the shipped markup — both handlers already bind. */
export type TileStatusRouteHandler = "data-home-app" | "data-route";

export interface TileStatusRouteAction {
  /** The word on the control. Always built from {@link TILE_STATUS_AUTHORED_TEXT}. */
  label: string;
  target: TileStatusRouteTarget;
  handler: TileStatusRouteHandler;
  /** The attribute value the handler reads. */
  handlerValue: string;
}

export interface TileStatusRoute {
  tileId: NativeAppId;
  /** The route this tile opens, as `route:tile`. */
  route: string;
  title: string;
  /** Generated by the backend. Not written here. */
  generatedLabel: string;
  capability: string;
  explanation: string;
  /** The thing worth doing about this status right now. */
  nextAction: TileStatusRouteAction;
  /** Where the proof behind the label is listed. */
  evidenceAction: TileStatusRouteAction;
  back: TileStatusRouteAction;
}

/**
 * Every string this module is allowed to write. `{app}` is the only hole, and
 * the display name from the catalog is the only thing that fills it.
 *
 * Adding a fifth entry is how a future promise would get in, which is why the
 * audit scans this list itself and not only the assembled route.
 */
export const TILE_STATUS_AUTHORED_TEXT = {
  openProfile: "Open {app} in a separate OSL profile",
  oslChat: "Write this in OSL Chat instead",
  evidence: "See what OSL has proven so far",
  back: "Back to Home",
} as const;

/**
 * Phrases that promise a future. Matched whole-word and case-insensitively, so
 * "will" does not fire inside "Willow" and "later" does not fire inside
 * "laterally".
 *
 * These are the shapes the app kept reaching for when it had nothing true to
 * say about a surface: a date it did not have, a plan it had not made, and in
 * WhatsApp's case (D-234) work that is not unfinished at all but refused.
 */
export const FUTURE_PROMISE_PHRASES: readonly string[] = [
  "coming soon",
  "coming later",
  "coming",
  "soon",
  "shortly",
  "eventually",
  "later",
  "in future",
  "in a future release",
  "future release",
  "future version",
  "next release",
  "upcoming",
  "planned",
  "roadmap",
  "stay tuned",
  "on the way",
  "in the works",
  "under way",
  "work in progress",
  "will be",
  "will support",
  "will let",
  "we will",
  "we'll",
  "promise",
  "arriving",
  "launching",
  "not yet supported",
];

function promiseRegex(phrase: string): RegExp {
  const body = phrase.replace(/[.*+?^${}()|[\]\\]/gu, "\\$&").replace(/\s+/gu, "\\s+");
  return new RegExp(`\\b${body}\\b`, "iu");
}

/** Every future-promise phrase present in one string, in list order. */
export function futurePromisesIn(text: string): string[] {
  return FUTURE_PROMISE_PHRASES.filter((phrase) => promiseRegex(phrase).test(text));
}

function action(
  label: string,
  target: TileStatusRouteTarget,
  handler: TileStatusRouteHandler,
  handlerValue: string,
): TileStatusRouteAction {
  return { label, target, handler, handlerValue };
}

/**
 * The one thing worth doing about this tile right now, decided from what OSL
 * can actually do on this device — never from the badge.
 *
 * An app OSL can open in its own profile gets that offer, because that is a
 * real, separate window a person can use in the next second. An app OSL cannot
 * open gets pointed at OSL Chat, which is the surface OSL has proven carries
 * messages both ways. Neither answer says anything about a future.
 */
export function tileStatusNextAction(app: NativeApp): TileStatusRouteAction {
  if (app.availability !== "unavailable" && app.isolatedProfileAvailable) {
    return action(
      TILE_STATUS_AUTHORED_TEXT.openProfile.replace("{app}", app.displayName),
      "service",
      "data-home-app",
      app.id,
    );
  }
  return action(TILE_STATUS_AUTHORED_TEXT.oslChat, "osl-chat", "data-route", "osl-chat");
}

/** One tile's status route, generated data and all. */
export function tileStatusRouteFor(app: NativeApp): TileStatusRoute {
  return {
    tileId: app.id,
    route: `service:${app.id}`,
    title: app.displayName,
    generatedLabel: app.statusPage.generatedLabel,
    capability: app.statusPage.capability,
    explanation: app.statusPage.explanation,
    nextAction: tileStatusNextAction(app),
    evidenceAction: action(TILE_STATUS_AUTHORED_TEXT.evidence, "connections", "data-route", "connections"),
    back: action(TILE_STATUS_AUTHORED_TEXT.back, "home", "data-route", "home"),
  };
}

/** Every tile's status route, in catalog order. */
export function tileStatusRoutes(apps: readonly NativeApp[]): TileStatusRoute[] {
  return apps.map((app) => tileStatusRouteFor(app));
}

export interface TileStatusRoutePromise {
  /** Which field the phrase was found in. */
  field: string;
  phrase: string;
  text: string;
}

export interface TileStatusRouteAudit {
  tileId: NativeAppId;
  /** Whether `generatedLabel` still is the label the status generates. */
  labelIsGenerated: boolean;
  /** Fields copied byte for byte out of the backend's status page. */
  generatedFields: { field: string; text: string }[];
  /** Fields this module wrote, plus any field that stopped matching its source. */
  handWrittenFields: { field: string; text: string }[];
  /** Future promises in the hand-written fields. Expected empty. */
  handWrittenPromises: TileStatusRoutePromise[];
  /** Future promises in the generated fields. Reported, not banned. */
  generatedPromises: TileStatusRoutePromise[];
}

/**
 * Split one route's prose into what the backend generated and what this module
 * wrote, then look for a future promise in each pile.
 *
 * A field counts as generated only while it still equals the value the catalog
 * carries for this app. Nothing here trusts the field's name.
 */
export function auditTileStatusRoute(app: NativeApp, route = tileStatusRouteFor(app)): TileStatusRouteAudit {
  const labelIsGenerated = route.generatedLabel === app.statusPage.generatedLabel
    && app.statusPage.generatedLabel === nativeAppGeneratedLabel(app.supportStatus);
  const fields: { field: string; text: string; generated: boolean }[] = [
    { field: "title", text: route.title, generated: route.title === app.displayName },
    { field: "generatedLabel", text: route.generatedLabel, generated: labelIsGenerated },
    { field: "capability", text: route.capability, generated: route.capability === app.statusPage.capability },
    { field: "explanation", text: route.explanation, generated: route.explanation === app.statusPage.explanation },
    { field: "nextAction.label", text: route.nextAction.label, generated: false },
    { field: "evidenceAction.label", text: route.evidenceAction.label, generated: false },
    { field: "back.label", text: route.back.label, generated: false },
  ];
  const promises = (generated: boolean): TileStatusRoutePromise[] =>
    fields
      .filter((entry) => entry.generated === generated)
      .flatMap((entry) => futurePromisesIn(entry.text).map((phrase) => ({ field: entry.field, phrase, text: entry.text })));
  return {
    tileId: route.tileId,
    labelIsGenerated,
    generatedFields: fields.filter((entry) => entry.generated).map(({ field, text }) => ({ field, text })),
    handWrittenFields: fields.filter((entry) => !entry.generated).map(({ field, text }) => ({ field, text })),
    handWrittenPromises: promises(false),
    generatedPromises: promises(true),
  };
}

/** {@link auditTileStatusRoute} over the whole catalog. */
export function auditTileStatusRoutes(apps: readonly NativeApp[]): TileStatusRouteAudit[] {
  return apps.map((app) => auditTileStatusRoute(app));
}
