//! REGISTER-FIX: prove the post-unlock / post-snowflake keyserver
//! registration hook runs the keyserver-client install that the
//! boot-time path skipped.
//!
//! Root cause being fixed: `bootstrap::run_autostart` runs at cold
//! boot. On a V2 clean install there is no `identity.json` then, so
//! the only boot-time caller of `client.register` + the only
//! installer of `state.keyserver` (`init_keyserver_and_register`) is
//! skipped, and nothing ever retried it — the machine never reached
//! `POST /v1/register`. The fix routes both the boot path and the
//! runtime paths through the shared
//! [`ipc::commands::ensure_keyserver_registered`].
//!
//! These tests are offline: `register` POSTs to an unreachable
//! loopback port so the network call fails fast. Per the helper's
//! non-fatal contract a `register` failure is swallowed and the
//! client is still installed (so later `fetch_pubkeys` can work) —
//! exactly the boot path's behaviour. We assert the *install*
//! happened, which is the half boot skipped; the POST itself is
//! exercised end-to-end against a real keyserver elsewhere.

use ipc::commands::ensure_keyserver_registered;
use ipc::AppState;

/// Unreachable on purpose: TCP port 1 refuses immediately, so
/// `register` returns a transport error in milliseconds instead of
/// waiting on the 30s client timeout.
const UNREACHABLE: &str = "http://127.0.0.1:1";

#[test]
fn post_unlock_registers_when_boot_skipped_it() {
    let state = AppState::new();

    // Precondition: this is exactly the state bootstrap leaves behind
    // when it skipped init_keyserver_and_register (no identity at
    // boot) — keyserver client absent.
    assert!(
        state.keyserver.lock().unwrap().is_none(),
        "precondition: keyserver client not installed (boot skipped it)"
    );

    // Identity now exists in state (loaded on relaunch by bootstrap,
    // or just generated by the Discord-snowflake path).
    *state.identity.lock().unwrap() = Some(keystore::generate_identity("123456789012345678".into()));

    ensure_keyserver_registered(&state, UNREACHABLE, None);

    // The register POST failed (offline) but, exactly like the boot
    // path, the client is installed regardless so fetch_pubkeys can
    // still work. This install is the work boot skipped — proving the
    // post-unlock hook closes the gap.
    assert!(
        state.keyserver.lock().unwrap().is_some(),
        "post-unlock hook must install the keyserver client that boot skipped"
    );
}

#[test]
fn no_identity_is_a_safe_noop() {
    let state = AppState::new();
    assert!(state.identity.lock().unwrap().is_none());

    // An unlock that happens before the Discord-snowflake identity
    // exists (first install: gate verifies before Discord opens).
    // Must not panic and must not install a client.
    ensure_keyserver_registered(&state, UNREACHABLE, None);

    assert!(
        state.keyserver.lock().unwrap().is_none(),
        "no identity → no-op: nothing to register, nothing installed"
    );
}

#[test]
fn idempotent_does_not_double_install_or_panic() {
    let state = AppState::new();
    *state.identity.lock().unwrap() = Some(keystore::generate_identity("123456789012345678".into()));

    // First call installs the client (boot-skipped recovery).
    ensure_keyserver_registered(&state, UNREACHABLE, None);
    assert!(state.keyserver.lock().unwrap().is_some());

    // This helper runs on EVERY unlock. Re-running must not panic and
    // must not stomp the already-installed client. (register itself
    // is a server-side upsert keyed by user_id with stable keys, so
    // the repeated POST is a no-op beyond a metadata timestamp.)
    ensure_keyserver_registered(&state, UNREACHABLE, None);
    ensure_keyserver_registered(&state, UNREACHABLE, None);
    assert!(
        state.keyserver.lock().unwrap().is_some(),
        "repeated unlocks keep exactly one installed client"
    );
}

#[test]
fn pre_installed_client_is_preserved() {
    // Simulates: bootstrap DID load an identity at boot and already
    // installed + registered (the dev-keyserver.json case requirement
    // #4 must not regress). A later password-gate unlock then fires
    // the same shared helper.
    let state = AppState::new();
    *state.identity.lock().unwrap() = Some(keystore::generate_identity("123456789012345678".into()));

    // Pretend boot installed it.
    *state.keyserver.lock().unwrap() =
        Some(keystore::KeyServerClient::new(UNREACHABLE).expect("client builds"));
    assert!(state.keyserver.lock().unwrap().is_some());

    // Post-unlock helper runs; must leave the boot-installed client
    // in place (no double-install / no overwrite).
    ensure_keyserver_registered(&state, UNREACHABLE, None);

    assert!(
        state.keyserver.lock().unwrap().is_some(),
        "an already-installed (boot) client must survive the post-unlock helper"
    );
}
