// Generated by scripts/build-uts39-wasm.sh from the pinned Rust UTS #39
// implementation.  This is deliberately a thin loader: policy lives in the
// Rust artifact so the Worker cannot acquire a second Unicode implementation.
import { analyze_identifier, initSync } from "./dist/osl_uts39_wasm.js";
import wasm from "./dist/osl_uts39_wasm_bg.wasm";

initSync({ module: wasm });

export type IdentifierAnalysis = Readonly<{
  normalized: string;
  skeleton: string;
  identifierAllowed: boolean;
  singleScript: boolean;
  restrictionLevel: "ascii-only" | "single-script" | "highly-restrictive" | "moderately-restrictive" | "minimally-restrictive" | "unrestricted";
  hasExcessMarks: boolean;
}>;

export function analyzeIdentifier(value: string): IdentifierAnalysis {
  const parsed: unknown = JSON.parse(analyze_identifier(value));
  if (typeof parsed !== "object" || parsed === null) throw new Error("UTS #39 artifact returned invalid JSON");
  const result = parsed as Record<string, unknown>;
  if (typeof result.normalized !== "string" || typeof result.skeleton !== "string" ||
      typeof result.identifierAllowed !== "boolean" || typeof result.singleScript !== "boolean" ||
      typeof result.restrictionLevel !== "string" || typeof result.hasExcessMarks !== "boolean") {
    throw new Error("UTS #39 artifact returned an invalid analysis");
  }
  return result as IdentifierAnalysis;
}
