// This module is generated by build-uts39-wasm.sh; dist/osl_uts39_wasm.d.ts is
// the checked-in declaration for it. The `@ts-expect-error` that used to stand
// here went stale once that declaration existed (TS2578) -- it was suppressing
// nothing, and it would have gone on hiding any real error on this import.
import init, { analyze_identifier } from "./dist/osl_uts39_wasm.js";

let initialized: Promise<void> | undefined;

function initialize(): Promise<void> {
  if (!initialized) initialized = init().then(() => undefined);
  return initialized!;
}

export default {
  async fetch(): Promise<Response> {
    await initialize();
    return Response.json(JSON.parse(analyze_identifier("pаypal")));
  },
};
