// @ts-expect-error This module is generated by build-uts39-wasm.sh.
import init, { analyze_identifier } from "./dist/osl_uts39_wasm.js";

let initialized: Promise<void> | undefined;

function initialize(): Promise<void> {
  if (!initialized) initialized = init().then(() => undefined);
  return initialized!;
}

export default {
  async fetch(): Promise<Response> {
    await initialize();
    return Response.json(JSON.parse(analyze_identifier("pаypal")));
  },
};
