#!/usr/bin/env python3
"""TASK 4709 -- run one real room-size trial and record raw artifacts only.

This script makes no pass/fail judgement about megabytes-per-hour; it only
runs real isolated OSL processes (one release LiveKit server + N speaker
clients, each a distinct OS process with a distinct PID and a distinct
synthetic participant key) exchanging real speech audio over the encrypted
WebRTC media transport, and it records the raw, unedited artifacts that
`derive.py` later turns into numbers:

  - immutable raw interface counters: /proc/<pid>/io (per participant
    process, sampled by THIS script, never self-reported by the speaker) and
    /proc/net/dev (system-wide, for the saturation/headroom cross-check)
  - packet timestamps: each speaker's own buffered send/receive event log,
    timestamped at the real call site, flushed only after the measurement
    window closes
  - process ids: pid of the server and of every speaker, with executable
    identity
  - distinct participant-key fingerprints: a fresh X25519 key generated by
    each speaker process
  - speech-source hashes: sha256 of the real speech recording each speaker
    plays
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import socket
import subprocess
import sys
import time
from pathlib import Path

TASK_ROOT = Path(__file__).resolve().parent
REPO_ROOT = TASK_ROOT.parents[1]
SPEECH_DIR = TASK_ROOT / "speech"
CACHE = Path("/tmp/osl-task-4701-cache")
LIVEKIT_SERVER_SHA256 = "51a1bbe04439b33d6d7a6d6d83fdefad9b938162c341f0f07f75af03e456b49a"
SPEAKER_BUILD_DIR = Path("/tmp/osl-task-4709-cache")

LIVEKIT_HOST = "127.0.0.1"
LIVEKIT_HTTP_PORT = 17890
LIVEKIT_API_KEY = "OSLTask4709Key"
LIVEKIT_API_SECRET = "OSLTask4709SecretAtLeast32BytesLong"


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def write_json(path: Path, value: object) -> None:
    path.write_text(json.dumps(value, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def build_speaker() -> Path:
    SPEAKER_BUILD_DIR.mkdir(parents=True, exist_ok=True)
    speaker = SPEAKER_BUILD_DIR / "osl-task-4709-speaker"
    go = CACHE / "go-1.26.5" / "bin" / "go"
    if not go.exists():
        raise RuntimeError(f"expected cached go toolchain at {go}, none found")
    env = os.environ.copy()
    env.update({"GOTOOLCHAIN": "local", "GOFLAGS": "-mod=mod", "PATH": f"{go.parent}:{env['PATH']}"})
    subprocess.run(
        [str(go), "build", "-buildvcs=false", "-trimpath", "-ldflags=-s -w", "-o", str(speaker), "."],
        cwd=TASK_ROOT / "speaker", env=env, check=True,
    )
    return speaker


def verify_server_binary() -> Path:
    server = CACHE / "livekit-server"
    if not server.exists():
        raise RuntimeError(f"expected cached livekit-server release binary at {server}, none found")
    actual = sha256_file(server)
    if actual != LIVEKIT_SERVER_SHA256:
        raise RuntimeError(f"livekit-server binary hash mismatch: expected={LIVEKIT_SERVER_SHA256} actual={actual}")
    version = subprocess.run([str(server), "--version"], text=True, capture_output=True, check=True).stdout.strip()
    if version != "livekit-server version 1.13.5":
        raise RuntimeError(f"unexpected release identity: {version}")
    return server


def proc_io(pid: int) -> dict[str, int]:
    text = Path(f"/proc/{pid}/io").read_text(encoding="utf-8")
    values: dict[str, int] = {}
    for line in text.splitlines():
        key, _, value = line.partition(":")
        values[key.strip()] = int(value.strip())
    return values


def proc_identity(role: str, pid: int, expected_exe: Path | None) -> dict[str, object]:
    proc = Path("/proc") / str(pid)
    executable = (proc / "exe").resolve()
    cmdline = (proc / "cmdline").read_bytes().split(b"\0")
    args = [item.decode("utf-8", "replace") for item in cmdline if item]
    args = ["<redacted-api-secret>" if item == LIVEKIT_API_SECRET else item for item in args]
    return {
        "role": role, "pid": pid, "executable": str(executable), "executable_sha256": sha256_file(executable),
        "expected_executable": str(expected_exe) if expected_exe else None, "cmdline": args,
        "start_ticks": (proc / "stat").read_text().split()[21],
    }


def net_dev_snapshot() -> dict[str, dict[str, int]]:
    result: dict[str, dict[str, int]] = {}
    for line in Path("/proc/net/dev").read_text(encoding="utf-8").splitlines()[2:]:
        name, rest = line.split(":", 1)
        fields = rest.split()
        result[name.strip()] = {
            "rx_bytes": int(fields[0]), "rx_packets": int(fields[1]),
            "tx_bytes": int(fields[8]), "tx_packets": int(fields[9]),
        }
    return result


def cpu_snapshot() -> dict[str, object]:
    stat_line = Path("/proc/stat").read_text(encoding="utf-8").splitlines()[0]
    fields = [int(value) for value in stat_line.split()[1:]]
    labels = ["user", "nice", "system", "idle", "iowait", "irq", "softirq", "steal"]
    named = dict(zip(labels, fields))
    loadavg = Path("/proc/loadavg").read_text(encoding="utf-8").split()
    mem = {}
    for line in Path("/proc/meminfo").read_text(encoding="utf-8").splitlines():
        key, _, value = line.partition(":")
        mem[key.strip()] = value.strip()
    return {
        "cpu_jiffies": named, "cpu_total_jiffies": sum(fields), "nproc": os.cpu_count(),
        "loadavg_1m": float(loadavg[0]), "loadavg_5m": float(loadavg[1]), "loadavg_15m": float(loadavg[2]),
        "mem_total_kb": int(mem["MemTotal"].split()[0]), "mem_available_kb": int(mem["MemAvailable"].split()[0]),
    }


def uplink_snapshot(iface: str) -> dict[str, object]:
    speed_path = Path(f"/sys/class/net/{iface}/speed")
    try:
        speed_mbps = int(speed_path.read_text().strip())
    except (OSError, ValueError):
        speed_mbps = None
    dev = net_dev_snapshot().get(iface, {})
    return {"interface": iface, "link_speed_mbps": speed_mbps, "rx_bytes": dev.get("rx_bytes"), "tx_bytes": dev.get("tx_bytes")}


def primary_uplink_interface() -> str:
    route = subprocess.run(["ip", "-o", "route", "get", "8.8.8.8"], text=True, capture_output=True, check=True).stdout
    parts = route.split()
    return parts[parts.index("dev") + 1]


def wait_for_port(host: str, port: int, timeout_s: float, extra_check) -> None:
    deadline = time.time() + timeout_s
    while time.time() < deadline:
        if extra_check() is not None:
            raise RuntimeError("process exited during startup")
        try:
            with socket.create_connection((host, port), timeout=0.2):
                return
        except OSError:
            time.sleep(0.05)
    raise RuntimeError(f"timed out waiting for {host}:{port}")


def run_trial(trial_name: str, room: str, participant_count: int, duration_seconds: int, artifacts_root: Path) -> Path:
    server = verify_server_binary()
    speaker = build_speaker()
    speaker_sha256 = sha256_file(speaker)

    artifacts = artifacts_root / trial_name
    if artifacts.exists():
        shutil.rmtree(artifacts)
    artifacts.mkdir(parents=True)
    runtime = artifacts / "runtime-workdir"
    runtime.mkdir()

    speech_files = sorted(SPEECH_DIR.glob("speech-*.ogg"))
    if len(speech_files) < 10:
        raise RuntimeError("expected 10 distinct real-speech source files")
    if participant_count > len(speech_files):
        raise RuntimeError("more participants requested than distinct speech sources available")

    identities = [f"speaker-{i:02d}" for i in range(participant_count)]
    speech_assignment = {identity: speech_files[i] for i, identity in enumerate(identities)}

    uplink_iface = primary_uplink_interface()

    processes: dict[str, subprocess.Popen] = {}
    handles: list[object] = []
    server_log = (artifacts / "livekit-server.txt").open("wb")
    handles.append(server_log)
    try:
        processes["livekit-server"] = subprocess.Popen(
            [str(server), "--config", str(TASK_ROOT / "config" / "livekit.yaml")],
            cwd=runtime, stdout=server_log, stderr=subprocess.STDOUT,
        )
        wait_for_port(LIVEKIT_HOST, LIVEKIT_HTTP_PORT, 15.0, lambda: processes["livekit-server"].poll())

        host_before = {
            "wall_unix_ns": time.time_ns(), "cpu": cpu_snapshot(),
            "uplink": uplink_snapshot(uplink_iface), "net_dev": net_dev_snapshot(),
        }

        coordinated_start_ns = time.time_ns() + 15_000_000_000
        events_paths: dict[str, Path] = {}
        for identity in identities:
            speech_path = speech_assignment[identity]
            events_path = artifacts / f"{identity}.events.jsonl"
            events_paths[identity] = events_path
            err_path = artifacts / f"{identity}.stderr.txt"
            err_handle = err_path.open("wb")
            handles.append(err_handle)
            processes[identity] = subprocess.Popen(
                [
                    str(speaker), "--host", f"ws://{LIVEKIT_HOST}:{LIVEKIT_HTTP_PORT}",
                    "--api-key", LIVEKIT_API_KEY, "--api-secret", LIVEKIT_API_SECRET,
                    "--room", room, "--identity", identity, "--speech-file", str(speech_path),
                    "--duration-seconds", str(duration_seconds),
                    "--start-unix-ns", str(coordinated_start_ns),
                    "--expected-peers", str(participant_count - 1),
                    "--events-out", str(events_path),
                ], cwd=runtime, stdout=subprocess.DEVNULL, stderr=err_handle,
            )

        # Let every participant connect, publish, and subscribe well before
        # the coordinated start; then take the pre-trial per-process counter
        # baseline right at the coordinated start instant.
        sleep_s = (coordinated_start_ns - time.time_ns()) / 1_000_000_000 - 0.5
        if sleep_s > 0:
            time.sleep(sleep_s)
        for role, process in processes.items():
            if process.poll() is not None:
                raise RuntimeError(f"{role} exited before trial start")
        while time.time_ns() < coordinated_start_ns:
            time.sleep(0.005)

        io_before = {identity: proc_io(processes[identity].pid) for identity in identities}
        net_dev_before = net_dev_snapshot()
        io_before_wall_ns = time.time_ns()

        identities_meta = [
            proc_identity(role, process.pid, server if role == "livekit-server" else speaker)
            for role, process in processes.items()
        ]
        write_json(artifacts / "process-identities.json", identities_meta)

        coordinated_end_ns = coordinated_start_ns + duration_seconds * 1_000_000_000
        sleep_s = (coordinated_end_ns - time.time_ns()) / 1_000_000_000 + 1.0
        if sleep_s > 0:
            time.sleep(sleep_s)
        for role in identities:
            if processes[role].poll() is not None:
                raise RuntimeError(f"{role} exited before the post-trial snapshot was taken")

        io_after = {identity: proc_io(processes[identity].pid) for identity in identities}
        net_dev_after = net_dev_snapshot()
        io_after_wall_ns = time.time_ns()
        host_during_end = {
            "wall_unix_ns": time.time_ns(), "cpu": cpu_snapshot(),
            "uplink": uplink_snapshot(uplink_iface), "net_dev": net_dev_after,
        }

        for identity in identities:
            status = processes[identity].wait(timeout=30)
            if status != 0:
                raise RuntimeError(f"{identity} exited {status}")

        host_after = {
            "wall_unix_ns": time.time_ns(), "cpu": cpu_snapshot(),
            "uplink": uplink_snapshot(uplink_iface), "net_dev": net_dev_snapshot(),
        }
    finally:
        process = processes.get("livekit-server")
        if process is not None and process.poll() is None:
            process.terminate()
            try:
                process.wait(timeout=10)
            except subprocess.TimeoutExpired:
                process.kill()
                process.wait()
        for handle in handles:
            handle.close()

    speech_hashes = {identity: sha256_file(path) for identity, path in speech_assignment.items()}
    speech_names = {identity: path.name for identity, path in speech_assignment.items()}

    write_json(artifacts / "interface-counters.json", {
        "counter_source": "/proc/<pid>/io (kernel per-process read/write syscall byte accounting)",
        "sampled_by": "orchestrator (measure.py), never self-reported by the speaker process",
        "io_before_wall_unix_ns": io_before_wall_ns, "io_after_wall_unix_ns": io_after_wall_ns,
        "io_before": io_before, "io_after": io_after,
    })
    write_json(artifacts / "net-dev-counters.json", {
        "counter_source": "/proc/net/dev (system-wide kernel interface counters)",
        "before": net_dev_before, "after": net_dev_after,
    })
    write_json(artifacts / "host-headroom.json", {
        "before": host_before, "trial_end": host_during_end, "after": host_after,
        "uplink_interface": uplink_iface,
    })
    write_json(artifacts / "trial-config.json", {
        "trial_name": trial_name, "room": room, "participant_count": participant_count,
        "identities": identities, "duration_seconds_requested": duration_seconds,
        "coordinated_start_unix_ns": coordinated_start_ns, "coordinated_end_unix_ns": coordinated_end_ns,
        "speech_source_files": speech_names, "speech_source_sha256": speech_hashes,
        "livekit_server_sha256": sha256_file(server), "livekit_server_version": "livekit-server version 1.13.5",
        "speaker_binary_sha256": speaker_sha256,
        "livekit_config_sha256": sha256_file(TASK_ROOT / "config" / "livekit.yaml"),
        "date": time.strftime("%Y-%m-%d", time.localtime(io_before_wall_ns / 1e9)),
        "build": "release LiveKit 1.13.5 (TASK 4701 qualified binary) + osl-task-4709-speaker",
    })

    required = [path for path in artifacts.rglob("*") if path.is_file() and path.name != "artifact-manifest.json"]
    manifest = {str(path.relative_to(artifacts)): sha256_file(path) for path in sorted(required)}
    write_json(artifacts / "artifact-manifest.json", manifest)
    return artifacts


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("trial_name")
    parser.add_argument("room")
    parser.add_argument("participant_count", type=int)
    parser.add_argument("--duration-seconds", type=int, default=120)
    parser.add_argument("--artifacts-root", type=Path, default=REPO_ROOT / "evidence" / "task-4709-voice-cost")
    args = parser.parse_args()
    artifacts = run_trial(args.trial_name, args.room, args.participant_count, args.duration_seconds, args.artifacts_root)
    print(f"TASK4709_TRIAL name={args.trial_name} artifacts={artifacts}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
