-- At-least-once, privacy-minimal delivery for operator payment alerts.
--
-- The deterministic alert id is a one-way digest generated by the Worker. It
-- is not an invoice id, claim token, address, transaction reference, customer
-- id, or chain identifier. The payload retains only the aggregate-safe facts
-- already used by commerce reporting.

CREATE TABLE payment_alert_outbox (
  alert_id TEXT PRIMARY KEY CHECK (
    length(alert_id) = 73
    AND substr(alert_id, 1, 9) = 'payalert_'
    AND substr(alert_id, 10) NOT GLOB '*[^0-9a-f]*'
  ),
  alert_kind TEXT NOT NULL CHECK (alert_kind IN ('crypto_pro', 'crypto_donation')),
  payment_method TEXT NOT NULL CHECK (payment_method IN ('btc', 'xmr')),
  amount_usd_cents INTEGER NOT NULL CHECK (
    typeof(amount_usd_cents) = 'integer'
    AND amount_usd_cents > 0
    AND amount_usd_cents <= 1000000
  ),
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'delivered')),
  attempts INTEGER NOT NULL DEFAULT 0 CHECK (attempts >= 0 AND attempts <= 1000),
  next_attempt_at INTEGER NOT NULL,
  created_at INTEGER NOT NULL,
  delivered_at INTEGER
);

CREATE INDEX idx_payment_alert_outbox_pending
  ON payment_alert_outbox (status, next_attempt_at, created_at);
