-- T21-C1 reservation: the Space event / invite lane owns 0041..0043.
-- The concrete event queue schema lands in T21-C5.  Keeping this migration
-- intentionally inert reserves the number without inventing a second
-- account-addressed transport before the frozen contract is implemented.
