//! B0-06: the 192-bit pointer cover must be produced by the trained bigram
//! arithmetic coder, not by the 6-bit / 64-word fixed substitution fallback.
//!
//! The two codecs are distinguishable without looking at any implementation
//! detail, purely from the emitted word stream:
//!
//!   * the substitution fallback maps each 6-bit group to `1 + value`, so it
//!     can only ever emit vocabulary indices 1..=64 — the upper half of the
//!     128-word vocabulary is unreachable by construction
//!     (`crates/stego/src/bigram.rs`, `wide_token_decode`);
//!   * the substitution fallback ignores the conditional model, so the mean
//!     surprisal `-log2 P(word | previous)` of its output is far above the
//!     model's own entropy rate (~5.05 bits/word, measured by
//!     `crates/cover-ai/tests/entropy_budget.rs`).
//!
//! An arithmetic coder driven by the model necessarily matches the model's
//! entropy rate — that is what makes it an arithmetic coder.

use stego::bigram::{self, VOCAB_SIZE};
use stego::{decode_token, encode_token, ConversationCipher, TOKEN_PAYLOAD_BITS};

/// Deterministic xorshift payload generator — no RNG crate, repeatable.
fn payload_bits(seed: u64, width: u32) -> Vec<bool> {
    let mut state = seed | 1;
    (0..width)
        .map(|_| {
            state ^= state << 13;
            state ^= state >> 7;
            state ^= state << 17;
            state & 1 == 1
        })
        .collect()
}

/// Mean `-log2 P(word | previous)` of a word stream under the shipped model.
fn mean_surprisal(words: &[usize]) -> f64 {
    let model = bigram::model();
    let mut prev = bigram::BOS_IDX;
    let mut total = 0.0f64;
    for &w in words {
        let row = &model.cum[prev];
        let denom = f64::from(row[VOCAB_SIZE - 1]);
        let count = f64::from(row[w] - if w == 0 { 0 } else { row[w - 1] });
        assert!(count > 0.0, "model assigned zero mass to an emitted word");
        total += -(count / denom).log2();
        prev = w;
    }
    total / words.len() as f64
}

#[test]
fn pointer_cover_uses_the_whole_vocabulary_not_the_64_word_substitution_table() {
    let mut seen_upper = 0usize;
    for seed in 0..512u64 {
        let bits = payload_bits(0xa5a5_0000_0000_0001 ^ seed, TOKEN_PAYLOAD_BITS);
        let words = bigram::arithmetic_decode_bits(&bits, TOKEN_PAYLOAD_BITS);
        seen_upper += words.iter().filter(|&&w| w > 64).count();
    }
    // The 6-bit substitution table cannot reach indices 65..=127 at all, so
    // any positive count here proves the model coder ran.
    assert!(
        seen_upper > 0,
        "no cover word came from the upper half of the vocabulary: the 6-bit \
         64-word substitution fallback is still generating the cover"
    );
}

#[test]
fn pointer_cover_tracks_the_model_entropy_rate() {
    // The shipped model's entropy rate is ~5.05 bits/word. A model-driven
    // arithmetic coder emits at that rate. The substitution fallback samples
    // uniformly from the 64 most frequent words with no regard for the
    // previous word, which the model scores far worse.
    let mut worst = 0.0f64;
    for seed in 0..128u64 {
        let bits = payload_bits(0x1357_9bdf_0000_0001 ^ (seed << 8), TOKEN_PAYLOAD_BITS);
        let words = bigram::arithmetic_decode_bits(&bits, TOKEN_PAYLOAD_BITS);
        let s = mean_surprisal(&words);
        if s > worst {
            worst = s;
        }
    }
    assert!(
        worst < 5.6,
        "mean surprisal {worst:.3} bits/word exceeds the model entropy rate: \
         the cover is not being generated by the trained model"
    );
}

#[test]
fn twenty_thousand_pointers_round_trip_bit_exact() {
    for case in 0..20_000u64 {
        let bits = payload_bits(0x9e37_79b9_7f4a_7c15 ^ case.wrapping_mul(0x2545_f491_4f6c_dd1d), TOKEN_PAYLOAD_BITS);
        let words = bigram::arithmetic_decode_bits(&bits, TOKEN_PAYLOAD_BITS);
        assert!(!words.is_empty(), "case {case} produced an empty cover");
        assert_eq!(
            bigram::arithmetic_encode_words(&words, TOKEN_PAYLOAD_BITS),
            bits,
            "case {case} did not round-trip bit-exact"
        );
        // Rendering and reparsing must also be lossless.
        let text = bigram::render_words(&words);
        assert_eq!(
            bigram::parse_words(&text).expect("own cover must parse"),
            words,
            "case {case} lost words through render/parse"
        );
    }
}

#[test]
fn full_pointer_path_round_trips_and_prints_samples() {
    let cipher = ConversationCipher::from_salt(b"b0-06-sample");
    let key = b"b0-06-detect-key";
    for n in 0..5u8 {
        let mut id = [0u8; 20];
        for (i, slot) in id.iter_mut().enumerate() {
            *slot = (i as u8).wrapping_mul(31).wrapping_add(n.wrapping_mul(97));
        }
        let cover = encode_token(&cipher, key, &id);
        println!(
            "[{} words] {}",
            cover.split_ascii_whitespace().count(),
            cover
        );
        assert_eq!(
            decode_token(&cipher, key, &cover),
            Some(id),
            "pointer {n} failed to decode from its own cover"
        );
    }
}

#[test]
fn a_single_flipped_payload_bit_changes_the_cover_and_the_decode() {
    let bits = payload_bits(0xfeed_face_0000_0001, TOKEN_PAYLOAD_BITS);
    let base = bigram::arithmetic_decode_bits(&bits, TOKEN_PAYLOAD_BITS);
    for flip in [0usize, 1, 47, 96, 159, 191] {
        let mut mutated = bits.clone();
        mutated[flip] = !mutated[flip];
        let words = bigram::arithmetic_decode_bits(&mutated, TOKEN_PAYLOAD_BITS);
        assert_ne!(words, base, "flipping bit {flip} left the cover unchanged");
        assert_eq!(
            bigram::arithmetic_encode_words(&words, TOKEN_PAYLOAD_BITS),
            mutated,
            "flipped-bit payload {flip} did not round-trip"
        );
    }
}
