//! T1-T33: pointer-v2 has enough shaped cover capacity for its full 24-byte wire.
//!
//! B0-06 note on the word-count assertion below. This test used to require the
//! shaped cover to be *exactly* `WIDE_TOKEN_WORDS` (32) words. That number was
//! never a capacity requirement — it was the arithmetic of the 6-bit /
//! 64-word substitution fallback (192 / 6 = 32), the codec that produced word
//! salad. Pinning it as an equality made the defect load-bearing: a cover
//! generated by the real model coder, whose length is payload-dependent by
//! construction, could not pass.
//!
//! The requirement T1-T33 protects is unchanged and still asserted: the full
//! 24-byte wire survives shaping and decodes back to the same pointer. The
//! word count is now bounded by a band derived from the model's measured
//! entropy rate instead of fixed to the fallback's constant, and the legacy
//! constant is still asserted for what it is — the width of the receive-only
//! compatibility path.

use stego::{
    bigram::WIDE_TOKEN_WORDS, decode_token, encode_token_shaped, rendered_rows, ConversationCipher,
    RowBudget, TOKEN_PAYLOAD_BITS,
};

#[test]
fn t1_t33_wide_pointer_round_trips_through_the_rebudgeted_cover() {
    let pointer = [0x5a; 20];
    let cipher = ConversationCipher::from_salt(b"t1-t33-cover-capacity");
    let detect_key = b"t1-t33-private-detect-key";
    let shaped = encode_token_shaped(&cipher, detect_key, &pointer, RowBudget::new(1, 40));

    assert_eq!(TOKEN_PAYLOAD_BITS, 192);
    // The legacy receive-only carrier is still 6 bits per word.
    assert_eq!(WIDE_TOKEN_WORDS, 32);

    // 192 bits at the model's measured ~5.05 bits/word entropy rate is ~38
    // words, plus up to a word of pinning slack per 64-bit chunk. The band is
    // wide enough not to be a hash of today's corpus and narrow enough to
    // catch a codec that has stopped tracking the model: the substitution
    // fallback lands on exactly 32 words for every pointer, under this floor.
    let words = shaped.text().split_whitespace().count();
    assert!(
        (34..=64).contains(&words),
        "shaped pointer cover is {words} words, outside the modelled band"
    );

    assert_eq!(shaped.rows, rendered_rows(shaped.text(), 40));
    assert_eq!(
        decode_token(&cipher, detect_key, shaped.text()),
        Some(pointer)
    );
}
