server=1
listen=0
discover=0
dnsseed=1
prune=12000
dbcache=1536
maxconnections=32
maxuploadtarget=5000
txindex=0
blockfilterindex=0
rpcbind=127.0.0.1
rpcallowip=127.0.0.1
rpcport=8332
rpccookiefile=/run/bitcoind/.cookie
rpccookieperms=group
